const vocabData = [
// L1: Basics
{ eng: "Hello", cantonese: "你好 (nei5 hou2)", level: 1 }, { eng: "Thank you (service)", cantonese: "唔該 (m4 goi1)", level: 1 }, { eng: "Thank you (gift)", cantonese: "多謝 (do1 ze6)", level: 1 }, { eng: "Yes", cantonese: "係 (hai6)", level: 1 }, { eng: "No", cantonese: "唔係 (m4 hai6)", level: 1 }, { eng: "I / Me", cantonese: "我 (ngo5)", level: 1 }, { eng: "You", cantonese: "你 (nei5)", level: 1 }, { eng: "He / She", cantonese: "佢 (keoi5)", level: 1 }, { eng: "Eat", cantonese: "食 (sik6)", level: 1 }, { eng: "Drink", cantonese: "飲 (jam2)", level: 1 }, { eng: "Water", cantonese: "水 (seoi2)", level: 1 }, { eng: "Tea", cantonese: "茶 (caa4)", level: 1 }, { eng: "Friend", cantonese: "朋友 (pang4 jau5)", level: 1 }, { eng: "Good", cantonese: "好 (hou2)", level: 1 }, { eng: "Goodbye", cantonese: "拜拜 (baai1 baai3)", level: 1 },
// L2: Numbers & Time
{ eng: "One", cantonese: "一 (jat1)", level: 2 }, { eng: "Two", cantonese: "二 (ji6)", level: 2 }, { eng: "Three", cantonese: "三 (saam1)", level: 2 }, { eng: "Four", cantonese: "四 (sei3)", level: 2 }, { eng: "Five", cantonese: "五 (ng5)", level: 2 }, { eng: "Six", cantonese: "六 (luk6)", level: 2 }, { eng: "Seven", cantonese: "七 (cat1)", level: 2 }, { eng: "Eight", cantonese: "八 (baat3)", level: 2 }, { eng: "Nine", cantonese: "九 (gau2)", level: 2 }, { eng: "Ten", cantonese: "十 (sap6)", level: 2 }, { eng: "Now", cantonese: "而家 (ji4 gaa1)", level: 2 }, { eng: "Morning", cantonese: "朝早 (ziu1 zou2)", level: 2 }, { eng: "Night", cantonese: "夜晚 (je6 maan5)", level: 2 }, { eng: "Tomorrow", cantonese: "聽日 (ting1 jat6)", level: 2 }, { eng: "Yesterday", cantonese: "尋日 (cam4 jat6)", level: 2 },
// L3: Places & Food
{ eng: "Restaurant", cantonese: "餐廳 (caan1 teng1)", level: 3 }, { eng: "School", cantonese: "學校 (hok6 gaau3)", level: 3 }, { eng: "Home", cantonese: "屋企 (uk1 kei2)", level: 3 }, { eng: "Work", cantonese: "返工 (faan1 gung1)", level: 3 }, { eng: "Buy", cantonese: "買 (maai5)", level: 3 }, { eng: "Sell", cantonese: "賣 (maai6)", level: 3 }, { eng: "Apple", cantonese: "蘋果 (ping4 guo2)", level: 3 }, { eng: "Rice", cantonese: "飯 (faan6)", level: 3 }, { eng: "Noodles", cantonese: "麵 (min6)", level: 3 }, { eng: "Delicious", cantonese: "好食 (hou2 sik6)", level: 3 }, { eng: "Hot", cantonese: "熱 (jit6)", level: 3 }, { eng: "Cold", cantonese: "凍 (dung3)", level: 3 }, { eng: "Big", cantonese: "大 (daai6)", level: 3 }, { eng: "Small", cantonese: "細 (sai3)", level: 3 }, { eng: "Money", cantonese: "錢 (cin2)", level: 3 },
// L4: Family & People
{ eng: "Father", cantonese: "爸爸 (baa4 baa1)", level: 4 }, { eng: "Mother", cantonese: "媽媽 (maa4 maa1)", level: 4 }, { eng: "Older Brother", cantonese: "哥哥 (go4 go1)", level: 4 }, { eng: "Younger Brother", cantonese: "細佬 (sai3 lou2)", level: 4 }, { eng: "Older Sister", cantonese: "家姐 (gaa1 ze1)", level: 4 }, { eng: "Younger Sister", cantonese: "細妹 (sai3 mui6)", level: 4 }, { eng: "Man", cantonese: "男人 (naam4 jan2)", level: 4 }, { eng: "Woman", cantonese: "女人 (neoi5 jan2)", level: 4 }, { eng: "Child", cantonese: "細路 (sai3 lou6)", level: 4 }, { eng: "Student", cantonese: "學生 (hok6 saang1)", level: 4 }, { eng: "Teacher", cantonese: "老師 (lou5 si1)", level: 4 }, { eng: "Doctor", cantonese: "醫生 (ji1 sang1)", level: 4 }, { eng: "Police", cantonese: "警察 (ging2 caat3)", level: 4 }, { eng: "Person", cantonese: "人 (jan4)", level: 4 }, { eng: "Name", cantonese: "名 (meng2)", level: 4 },
// L5: Body & Health
{ eng: "Head", cantonese: "頭 (tau4)", level: 5 }, { eng: "Eye", cantonese: "眼 (ngaan5)", level: 5 }, { eng: "Ear", cantonese: "耳仔 (ji5 zai2)", level: 5 }, { eng: "Nose", cantonese: "鼻 (bei6)", level: 5 }, { eng: "Mouth", cantonese: "口 (hau2)", level: 5 }, { eng: "Hand", cantonese: "手 (sau2)", level: 5 }, { eng: "Foot", cantonese: "腳 (goek3)", level: 5 }, { eng: "Hair", cantonese: "頭髮 (tau4 faat3)", level: 5 }, { eng: "Face", cantonese: "面 (min6)", level: 5 }, { eng: "Stomach", cantonese: "胃 (wai6)", level: 5 }, { eng: "Pain", cantonese: "痛 (tung3)", level: 5 }, { eng: "Sick", cantonese: "病 (beng6)", level: 5 }, { eng: "Hospital", cantonese: "醫院 (ji1 jyun2)", level: 5 }, { eng: "Medicine", cantonese: "藥 (joek6)", level: 5 }, { eng: "Sleep", cantonese: "瞓覺 (fan3 gaau3)", level: 5 },
// L6: Transport & Directions
{ eng: "Car", cantonese: "車 (ce1)", level: 6 }, { eng: "Bus", cantonese: "巴士 (baa1 si2)", level: 6 }, { eng: "Train", cantonese: "火車 (fo2 ce1)", level: 6 }, { eng: "Subway", cantonese: "地鐵 (dei6 tit3)", level: 6 }, { eng: "Taxi", cantonese: "的士 (dik1 si2)", level: 6 }, { eng: "Plane", cantonese: "飛機 (fei1 gei1)", level: 6 }, { eng: "Road", cantonese: "路 (lou6)", level: 6 }, { eng: "Left", cantonese: "左 (zo2)", level: 6 }, { eng: "Right", cantonese: "右 (jau6)", level: 6 }, { eng: "Straight", cantonese: "直 (zik6)", level: 6 }, { eng: "Front", cantonese: "前 (cin4)", level: 6 }, { eng: "Back", cantonese: "後 (hau6)", level: 6 }, { eng: "Up", cantonese: "上 (soeng6)", level: 6 }, { eng: "Down", cantonese: "下 (haa6)", level: 6 }, { eng: "Map", cantonese: "地圖 (dei6 tou4)", level: 6 },

// L7: Animals
{ eng: "Dog", cantonese: "狗 (gau2)", level: 7 },
{ eng: "Cat", cantonese: "貓 (maau1)", level: 7 },
{ eng: "Bird", cantonese: "雀仔 (zoek3 zai2)", level: 7 },
{ eng: "Fish", cantonese: "魚 (jyu2)", level: 7 },
{ eng: "Cow", cantonese: "牛 (ngau4)", level: 7 },
{ eng: "Pig", cantonese: "豬 (zyu1)", level: 7 },
{ eng: "Chicken", cantonese: "雞 (gai1)", level: 7 },
{ eng: "Horse", cantonese: "馬 (maa5)", level: 7 },
{ eng: "Sheep", cantonese: "羊 (joeng4)", level: 7 },
{ eng: "Mouse", cantonese: "老鼠 (lou5 syu2)", level: 7 },
{ eng: "Tiger", cantonese: "老虎 (lou5 fu2)", level: 7 },
{ eng: "Lion", cantonese: "獅子 (si1 zi2)", level: 7 },
{ eng: "Elephant", cantonese: "大象 (daai6 zoeng6)", level: 7 },
{ eng: "Monkey", cantonese: "馬騮 (maa5 lau1)", level: 7 },
{ eng: "Bear", cantonese: "熊 (hung4)", level: 7 },

// L8: Colors & Weather
{ eng: "Color", cantonese: "顏色 (ngaan4 sik1)", level: 8 },
{ eng: "Red", cantonese: "紅色 (hung4 sik1)", level: 8 },
{ eng: "Blue", cantonese: "藍色 (laam4 sik1)", level: 8 },
{ eng: "Yellow", cantonese: "黃色 (wong4 sik1)", level: 8 },
{ eng: "Green", cantonese: "綠色 (luk6 sik1)", level: 8 },
{ eng: "Black", cantonese: "黑色 (hak1 sik1)", level: 8 },
{ eng: "White", cantonese: "白色 (baak6 sik1)", level: 8 },
{ eng: "Weather", cantonese: "天氣 (tin1 hei3)", level: 8 },
{ eng: "Sun", cantonese: "太陽 (taai3 joeng4)", level: 8 },
{ eng: "Rain", cantonese: "落雨 (lok6 jyu5)", level: 8 },
{ eng: "Wind", cantonese: "風 (fung1)", level: 8 },
{ eng: "Snow", cantonese: "落雪 (lok6 syut3)", level: 8 },
{ eng: "Cloud", cantonese: "雲 (wan4)", level: 8 },
{ eng: "Sky", cantonese: "天 (tin1)", level: 8 },
{ eng: "Moon", cantonese: "月亮 (jyut6 loeng6)", level: 8 },

// L9: Clothes & Accessories
{ eng: "Clothes", cantonese: "衫 (saam1)", level: 9 },
{ eng: "Shirt", cantonese: "恤衫 (seot1 saam1)", level: 9 },
{ eng: "Pants", cantonese: "褲 (fu3)", level: 9 },
{ eng: "Skirt", cantonese: "裙 (kwan4)", level: 9 },
{ eng: "Shoe", cantonese: "鞋 (haai4)", level: 9 },
{ eng: "Sock", cantonese: "襪 (mat6)", level: 9 },
{ eng: "Hat", cantonese: "帽 (mou2)", level: 9 },
{ eng: "Glasses", cantonese: "眼鏡 (ngaan5 geng2)", level: 9 },
{ eng: "Coat / Jacket", cantonese: "外套 (ngoi6 tou3)", level: 9 },
{ eng: "Bag", cantonese: "袋 (doi2)", level: 9 },
{ eng: "Watch", cantonese: "錶 (biu1)", level: 9 },
{ eng: "Ring", cantonese: "戒指 (gaai3 zi2)", level: 9 },
{ eng: "Umbrella", cantonese: "遮 (ze1)", level: 9 },
{ eng: "Wallet", cantonese: "銀包 (ngan4 baau1)", level: 9 },
{ eng: "Necklace", cantonese: "頸鏈 (geng2 lin2)", level: 9 },

// L10: Home & Furniture
{ eng: "Door", cantonese: "門 (mun4)", level: 10 },
{ eng: "Window", cantonese: "窗 (coeng1)", level: 10 },
{ eng: "Bed", cantonese: "床 (cong4)", level: 10 },
{ eng: "Chair", cantonese: "凳 (dang3)", level: 10 },
{ eng: "Table", cantonese: "枱 (toi2)", level: 10 },
{ eng: "Sofa", cantonese: "梳化 (so1 faa2)", level: 10 },
{ eng: "Television", cantonese: "電視 (din6 si6)", level: 10 },
{ eng: "Computer", cantonese: "電腦 (din6 nou5)", level: 10 },
{ eng: "Phone", cantonese: "電話 (din6 waa2)", level: 10 },
{ eng: "Light / Lamp", cantonese: "燈 (dang1)", level: 10 },
{ eng: "Kitchen", cantonese: "廚房 (cyu4 fong2)", level: 10 },
{ eng: "Bathroom", cantonese: "廁所 (ci3 so2)", level: 10 },
{ eng: "Room", cantonese: "房 (fong2)", level: 10 },
{ eng: "Key", cantonese: "鎖匙 (so2 si4)", level: 10 },
{ eng: "Picture / Photo", cantonese: "相 (soeng2)", level: 10 },

// L11: Action Verbs (Intermediate Tier Starts)
{ eng: "Go", cantonese: "去 (heoi3)", level: 11 },
{ eng: "Come", cantonese: "嚟 (lai4)", level: 11 },
{ eng: "Look / See", cantonese: "睇 (tai2)", level: 11 },
{ eng: "Listen / Hear", cantonese: "聽 (ting1)", level: 11 },
{ eng: "Speak / Say", cantonese: "講 (gong2)", level: 11 },
{ eng: "Read", cantonese: "讀 (duk6)", level: 11 },
{ eng: "Write", cantonese: "寫 (se2)", level: 11 },
{ eng: "Walk", cantonese: "行 (haang4)", level: 11 },
{ eng: "Run", cantonese: "跑 (paau2)", level: 11 },
{ eng: "Sit", cantonese: "坐 (co5)", level: 11 },
{ eng: "Stand", cantonese: "企 (kei5)", level: 11 },
{ eng: "Give", cantonese: "畀 (bei2)", level: 11 },
{ eng: "Take / Get", cantonese: "攞 (lo2)", level: 11 },
{ eng: "Wait", cantonese: "等 (dang2)", level: 11 },
{ eng: "Help", cantonese: "幫 (bong1)", level: 11 },

// L12: Adjectives & Emotions
{ eng: "Happy", cantonese: "開心 (hoi1 sam1)", level: 12 },
{ eng: "Sad", cantonese: "傷心 (soeng1 sam1)", level: 12 },
{ eng: "Angry", cantonese: "嬲 (nau1)", level: 12 },
{ eng: "Tired", cantonese: "攰 (gui6)", level: 12 },
{ eng: "Fast", cantonese: "快 (faai3)", level: 12 },
{ eng: "Slow", cantonese: "慢 (maan6)", level: 12 },
{ eng: "Expensive", cantonese: "貴 (gwai3)", level: 12 },
{ eng: "Cheap", cantonese: "平 (peng4)", level: 12 },
{ eng: "Beautiful / Pretty", cantonese: "靚 (leng3)", level: 12 },
{ eng: "Ugly", cantonese: "樣衰 (joeng2 seoi1)", level: 12 },
{ eng: "New", cantonese: "新 (san1)", level: 12 },
{ eng: "Old (objects)", cantonese: "舊 (gau6)", level: 12 },
{ eng: "Long", cantonese: "長 (coeng4)", level: 12 },
{ eng: "Short", cantonese: "短 (dyun2)", level: 12 },
{ eng: "Heavy", cantonese: "重 (cung5)", level: 12 },

// L13: Food & Drinks II
{ eng: "Bread", cantonese: "麵包 (min6 baau1)", level: 13 },
{ eng: "Egg", cantonese: "蛋 (daan2)", level: 13 },
{ eng: "Meat", cantonese: "肉 (juk6)", level: 13 },
{ eng: "Beef", cantonese: "牛肉 (ngau4 juk6)", level: 13 },
{ eng: "Pork", cantonese: "豬肉 (zyu1 juk6)", level: 13 },
{ eng: "Chicken (meat)", cantonese: "雞肉 (gai1 juk6)", level: 13 },
{ eng: "Fish (food)", cantonese: "魚肉 (jyu2 juk6)", level: 13 },
{ eng: "Vegetable", cantonese: "菜 (coi3)", level: 13 },
{ eng: "Fruit", cantonese: "生果 (saang1 gwo2)", level: 13 },
{ eng: "Milk", cantonese: "牛奶 (ngau4 naai5)", level: 13 },
{ eng: "Coffee", cantonese: "咖啡 (gaa3 fe1)", level: 13 },
{ eng: "Sugar", cantonese: "糖 (tong4)", level: 13 },
{ eng: "Salt", cantonese: "鹽 (jim4)", level: 13 },
{ eng: "Soup", cantonese: "湯 (tong1)", level: 13 },
{ eng: "Cake", cantonese: "蛋糕 (daan6 gou1)", level: 13 },

// L14: Daily Activities
{ eng: "Wake up", cantonese: "起身 (hei2 san1)", level: 14 },
{ eng: "Wash face", cantonese: "洗面 (sai2 min6)", level: 14 },
{ eng: "Brush teeth", cantonese: "刷牙 (caat3 ngaa4)", level: 14 },
{ eng: "Take a shower", cantonese: "沖涼 (cung1 loeng4)", level: 14 },
{ eng: "Go to school", cantonese: "返學 (faan1 hok6)", level: 14 },
{ eng: "Get off work", cantonese: "放工 (fong3 gung1)", level: 14 },
{ eng: "Rest", cantonese: "休息 (jau1 sik1)", level: 14 },
{ eng: "Play", cantonese: "玩 (waan2)", level: 14 },
{ eng: "Watch TV", cantonese: "睇電視 (tai2 din6 si6)", level: 14 },
{ eng: "Wash clothes", cantonese: "洗衫 (sai2 saam1)", level: 14 },
{ eng: "Clean up", cantonese: "執嘢 (zap1 je5)", level: 14 },
{ eng: "Cook", cantonese: "煮飯 (zyu2 faan6)", level: 14 },
{ eng: "Buy things / Shop", cantonese: "買嘢 (maai5 je5)", level: 14 },
{ eng: "Do homework", cantonese: "做功課 (zou6 gung1 fo3)", level: 14 },
{ eng: "Sing", cantonese: "唱歌 (coeng3 go1)", level: 14 },

// L15: Time & Calendar
{ eng: "Time", cantonese: "時間 (si4 gaan3)", level: 15 },
{ eng: "Clock", cantonese: "鐘 (zung1)", level: 15 },
{ eng: "Minute", cantonese: "分鐘 (fan1 zung1)", level: 15 },
{ eng: "Hour", cantonese: "鐘頭 (zung1 tau4)", level: 15 },
{ eng: "Day", cantonese: "日 (jat6)", level: 15 },
{ eng: "Week", cantonese: "星期 (sing1 kei4)", level: 15 },
{ eng: "Month", cantonese: "月 (jyut6)", level: 15 },
{ eng: "Year", cantonese: "年 (nin4)", level: 15 },
{ eng: "Today", cantonese: "今日 (gam1 jat6)", level: 15 },
{ eng: "This year", cantonese: "今年 (gam1 nin4)", level: 15 },
{ eng: "Next year", cantonese: "出年 (ceot1 nin4)", level: 15 },
{ eng: "Last year", cantonese: "舊年 (gau6 nin4)", level: 15 },
{ eng: "Weekend", cantonese: "週末 (zau1 mut6)", level: 15 },
{ eng: "Holiday", cantonese: "假期 (gaa3 kei4)", level: 15 },
{ eng: "Birthday", cantonese: "生日 (saang1 jat6)", level: 15 },

// L16: City & Places
{ eng: "City", cantonese: "城市 (sing4 si5)", level: 16 },
{ eng: "Street", cantonese: "街 (gaai1)", level: 16 },
{ eng: "Shop / Store", cantonese: "舖頭 (pou3 tau4)", level: 16 },
{ eng: "Supermarket", cantonese: "超級市場 (ciu1 kap1 si5 coeng4)", level: 16 },
{ eng: "Market", cantonese: "街市 (gaai1 si5)", level: 16 },
{ eng: "Bank", cantonese: "銀行 (ngan4 hong4)", level: 16 },
{ eng: "Park", cantonese: "公園 (gung1 jyun2)", level: 16 },
{ eng: "Cinema", cantonese: "戲院 (hei3 jyun2)", level: 16 },
{ eng: "Hotel", cantonese: "酒店 (zau2 dim3)", level: 16 },
{ eng: "Airport", cantonese: "機場 (gei1 coeng4)", level: 16 },
{ eng: "Station", cantonese: "站 (zaam6)", level: 16 },
{ eng: "Library", cantonese: "圖書館 (tou4 syu1 gun2)", level: 16 },
{ eng: "Beach", cantonese: "沙灘 (saa1 taan1)", level: 16 },
{ eng: "Mountain", cantonese: "山 (saan1)", level: 16 },
{ eng: "Company / Office", cantonese: "公司 (gung1 si1)", level: 16 },

// L17: Nature & Materials
{ eng: "Tree", cantonese: "樹 (syu6)", level: 17 },
{ eng: "Flower", cantonese: "花 (faa1)", level: 17 },
{ eng: "Grass", cantonese: "草 (cou2)", level: 17 },
{ eng: "Leaf", cantonese: "葉 (jip6)", level: 17 },
{ eng: "Stone / Rock", cantonese: "石頭 (sek6 tau4)", level: 17 },
{ eng: "Wood", cantonese: "木 (muk6)", level: 17 },
{ eng: "Paper", cantonese: "紙 (zi2)", level: 17 },
{ eng: "Glass", cantonese: "玻璃 (bo1 lei1)", level: 17 },
{ eng: "Metal", cantonese: "金屬 (gam1 suk6)", level: 17 },
{ eng: "Plastic", cantonese: "塑膠 (sou3 gaau1)", level: 17 },
{ eng: "Fire", cantonese: "火 (fo2)", level: 17 },
{ eng: "Earth / Dirt", cantonese: "泥 (nai4)", level: 17 },
{ eng: "Air", cantonese: "空氣 (hung1 hei3)", level: 17 },
{ eng: "Light", cantonese: "光 (gwong1)", level: 17 },
{ eng: "Shadow", cantonese: "影 (jing2)", level: 17 },

// L18: Positions & Directions
{ eng: "Inside", cantonese: "入面 (jap6 min6)", level: 18 },
{ eng: "Outside", cantonese: "出面 (ceot1 min6)", level: 18 },
{ eng: "Top / Above", cantonese: "上面 (soeng6 min6)", level: 18 },
{ eng: "Bottom / Below", cantonese: "下面 (haa6 min6)", level: 18 },
{ eng: "Middle", cantonese: "中間 (zung1 gaan1)", level: 18 },
{ eng: "Beside / Next to", cantonese: "隔籬 (gaak3 lei4)", level: 18 },
{ eng: "Nearby", cantonese: "附近 (fu6 gan6)", level: 18 },
{ eng: "Far", cantonese: "遠 (jyun5)", level: 18 },
{ eng: "Near", cantonese: "近 (gan6)", level: 18 },
{ eng: "Opposite", cantonese: "對面 (deoi3 min6)", level: 18 },
{ eng: "East", cantonese: "東 (dung1)", level: 18 },
{ eng: "West", cantonese: "西 (sai1)", level: 18 },
{ eng: "South", cantonese: "南 (naam4)", level: 18 },
{ eng: "North", cantonese: "北 (bak1)", level: 18 },
{ eng: "Direction", cantonese: "方向 (fong1 hoeng3)", level: 18 },

// L19: Occupations & Roles
{ eng: "Boss", cantonese: "老闆 (lou5 baan2)", level: 19 },
{ eng: "Manager", cantonese: "經理 (ging1 lei5)", level: 19 },
{ eng: "Employee", cantonese: "員工 (jyun4 gung1)", level: 19 },
{ eng: "Colleague", cantonese: "同事 (tung4 si6)", level: 19 },
{ eng: "Customer", cantonese: "客 (haak3)", level: 19 },
{ eng: "Scientist", cantonese: "科學家 (fo1 hok6 gaa1)", level: 19 },
{ eng: "Engineer", cantonese: "工程師 (gung1 cing4 si1)", level: 19 },
{ eng: "Driver", cantonese: "司機 (si1 gei1)", level: 19 },
{ eng: "Chef", cantonese: "廚師 (cyu4 si1)", level: 19 },
{ eng: "Waiter", cantonese: "侍應 (si6 jing3)", level: 19 },
{ eng: "Nurse", cantonese: "護士 (wu6 si6)", level: 19 },
{ eng: "Dentist", cantonese: "牙醫 (ngaa4 ji1)", level: 19 },
{ eng: "Writer", cantonese: "作家 (zok3 gaa1)", level: 19 },
{ eng: "Artist", cantonese: "藝術家 (ngai6 seot6 gaa1)", level: 19 },
{ eng: "Actor", cantonese: "演員 (jin2 jyun4)", level: 19 },

// L20: Communication & Technology
{ eng: "Message", cantonese: "短訊 (dyun2 seon3)", level: 20 },
{ eng: "Internet", cantonese: "上網 (soeng5 mong5)", level: 20 },
{ eng: "Website", cantonese: "網站 (mong5 zaam6)", level: 20 },
{ eng: "Password", cantonese: "密碼 (mat6 maa5)", level: 20 },
{ eng: "Screen", cantonese: "熒幕 (jing4 mok6)", level: 20 },
{ eng: "Keyboard", cantonese: "鍵盤 (gin6 pun4)", level: 20 },
{ eng: "Button", cantonese: "掣 (zai3)", level: 20 },
{ eng: "App", cantonese: "應用程式 (jing3 jung6 cing4 sik1)", level: 20 },
{ eng: "Camera", cantonese: "相機 (soeng2 gei1)", level: 20 },
{ eng: "Photograph", cantonese: "相片 (soeng2 pin2)", level: 20 },
{ eng: "Video", cantonese: "影片 (jing2 pin2)", level: 20 },
{ eng: "Game", cantonese: "遊戲 (jau4 hei3)", level: 20 },
{ eng: "News", cantonese: "新聞 (san1 man4)", level: 20 },
{ eng: "Music", cantonese: "音樂 (jam1 ngok6)", level: 20 },
{ eng: "Movie", cantonese: "電影 (din6 jing2)", level: 20 },

// L21: Abstract Concepts (Hard Tier Starts)
{ eng: "Idea", cantonese: "想法 (soeng2 faat3)", level: 21 },
{ eng: "Reason", cantonese: "原因 (jyun4 jan1)", level: 21 },
{ eng: "Method", cantonese: "方法 (fong1 faat3)", level: 21 },
{ eng: "Result", cantonese: "結果 (git3 gwo2)", level: 21 },
{ eng: "Problem", cantonese: "問題 (man6 tai4)", level: 21 },
{ eng: "Solution", cantonese: "解決辦法 (gaai2 kyut3 baan6 faat3)", level: 21 },
{ eng: "Opportunity", cantonese: "機會 (gei1 wui6)", level: 21 },
{ eng: "Success", cantonese: "成功 (sing4 gung1)", level: 21 },
{ eng: "Failure", cantonese: "失敗 (sat1 baai6)", level: 21 },
{ eng: "Truth", cantonese: "真相 (zan1 soeng3)", level: 21 },
{ eng: "Lie", cantonese: "大話 (daai6 waa6)", level: 21 },
{ eng: "Secret", cantonese: "秘密 (bei3 mat6)", level: 21 },
{ eng: "Dream", cantonese: "夢想 (mung6 soeng2)", level: 21 },
{ eng: "Memory", cantonese: "記憶 (gei3 jik1)", level: 21 },
{ eng: "Experience", cantonese: "經驗 (ging1 jim6)", level: 21 },

// L22: Finances & Business
{ eng: "Price", cantonese: "價錢 (gaa3 cin4)", level: 22 },
{ eng: "Discount", cantonese: "折 (zit3)", level: 22 },
{ eng: "Cash", cantonese: "現金 (jin6 gam1)", level: 22 },
{ eng: "Credit Card", cantonese: "信用卡 (seon3 jung6 kaat1)", level: 22 },
{ eng: "Receipt", cantonese: "收據 (sau1 geoi3)", level: 22 },
{ eng: "Account", cantonese: "戶口 (wu6 hau2)", level: 22 },
{ eng: "Tax", cantonese: "稅 (seoi3)", level: 22 },
{ eng: "Salary", cantonese: "人工 (jan4 gung1)", level: 22 },
{ eng: "Profit", cantonese: "利潤 (lei6 jeon6)", level: 22 },
{ eng: "Loss", cantonese: "損失 (syun2 sat1)", level: 22 },
{ eng: "Contract", cantonese: "合約 (hap6 joek3)", level: 22 },
{ eng: "Meeting", cantonese: "開會 (hoi1 wui2)", level: 22 },
{ eng: "Sign (Signature)", cantonese: "簽名 (cim1 ming2)", level: 22 },
{ eng: "Investment", cantonese: "投資 (tau4 zi1)", level: 22 },
{ eng: "Economy", cantonese: "經濟 (ging1 zai3)", level: 22 },

// L23: Shapes & Math
{ eng: "Shape", cantonese: "形狀 (jing4 zong6)", level: 23 },
{ eng: "Circle", cantonese: "圓形 (jyun4 jing4)", level: 23 },
{ eng: "Square", cantonese: "正方形 (zing3 fong1 jing4)", level: 23 },
{ eng: "Triangle", cantonese: "三角形 (saam1 gok3 jing4)", level: 23 },
{ eng: "Line", cantonese: "線 (sin3)", level: 23 },
{ eng: "Point", cantonese: "點 (dim2)", level: 23 },
{ eng: "Add", cantonese: "加 (gaa1)", level: 23 },
{ eng: "Subtract", cantonese: "減 (gaam2)", level: 23 },
{ eng: "Multiply", cantonese: "乘 (sing4)", level: 23 },
{ eng: "Divide", cantonese: "除 (ceoi4)", level: 23 },
{ eng: "Half", cantonese: "一半 (jat1 bun3)", level: 23 },
{ eng: "Number", cantonese: "數字 (sou3 zi6)", level: 23 },
{ eng: "Count", cantonese: "數 (sou2)", level: 23 },
{ eng: "Weight", cantonese: "重量 (cung5 loeng6)", level: 23 },
{ eng: "Measure", cantonese: "量度 (loeng4 dok6)", level: 23 },

// L24: Body Movements & Actions
{ eng: "Push", cantonese: "推 (teoi1)", level: 24 },
{ eng: "Pull", cantonese: "拉 (laai1)", level: 24 },
{ eng: "Throw", cantonese: "掉 (diu6)", level: 24 },
{ eng: "Catch", cantonese: "接 (zip3)", level: 24 },
{ eng: "Jump", cantonese: "跳 (tiu3)", level: 24 },
{ eng: "Kick", cantonese: "踢 (tek3)", level: 24 },
{ eng: "Hit", cantonese: "打 (daa2)", level: 24 },
{ eng: "Touch", cantonese: "摸 (mo2)", level: 24 },
{ eng: "Hold", cantonese: "拎 (ling1)", level: 24 },
{ eng: "Drop", cantonese: "跌 (dit3)", level: 24 },
{ eng: "Open", cantonese: "開 (hoi1)", level: 24 },
{ eng: "Close", cantonese: "閂 (saan1)", level: 24 },
{ eng: "Break", cantonese: "打爛 (daa2 laan6)", level: 24 },
{ eng: "Fix", cantonese: "整 (zing2)", level: 24 },
{ eng: "Build", cantonese: "起 (hei2)", level: 24 },

// L25: Social & Relationships
{ eng: "Love", cantonese: "愛 (oi3)", level: 25 },
{ eng: "Hate", cantonese: "憎 (zang1)", level: 25 },
{ eng: "Marry", cantonese: "結婚 (git3 fan1)", level: 25 },
{ eng: "Divorce", cantonese: "離婚 (lei4 fan1)", level: 25 },
{ eng: "Promise", cantonese: "應承 (jing1 sing4)", level: 25 },
{ eng: "Apologize", cantonese: "道歉 (dou6 hip3)", level: 25 },
{ eng: "Forgive", cantonese: "原諒 (jyun4 loeng6)", level: 25 },
{ eng: "Argue", cantonese: "嗌交 (aai3 gaau1)", level: 25 },
{ eng: "Agree", cantonese: "同意 (tung4 ji3)", level: 25 },
{ eng: "Disagree", cantonese: "唔同意 (m4 tung4 ji3)", level: 25 },
{ eng: "Trust", cantonese: "相信 (soeng1 seon3)", level: 25 },
{ eng: "Doubt", cantonese: "懷疑 (waai4 ji4)", level: 25 },
{ eng: "Respect", cantonese: "尊重 (zyun1 zung6)", level: 25 },
{ eng: "Joke", cantonese: "講笑 (gong2 siu3)", level: 25 },
{ eng: "Share", cantonese: "分享 (fan1 hoeng2)", level: 25 },

// L26: Travel & Geography
{ eng: "Passport", cantonese: "護照 (wu6 ziu3)", level: 26 },
{ eng: "Visa", cantonese: "簽證 (cim1 zing3)", level: 26 },
{ eng: "Luggage", cantonese: "行李 (hang4 lei5)", level: 26 },
{ eng: "Ticket", cantonese: "飛 (fei1)", level: 26 },
{ eng: "Flight", cantonese: "航班 (hong4 bun1)", level: 26 },
{ eng: "Country", cantonese: "國家 (gwok3 gaa1)", level: 26 },
{ eng: "Capital", cantonese: "首都 (sau2 dou1)", level: 26 },
{ eng: "Border", cantonese: "邊境 (bin1 ging2)", level: 26 },
{ eng: "Ocean", cantonese: "海 (hoi2)", level: 26 },
{ eng: "Island", cantonese: "島 (dou2)", level: 26 },
{ eng: "Desert", cantonese: "沙漠 (saa1 mok6)", level: 26 },
{ eng: "Forest", cantonese: "森林 (sam1 lam4)", level: 26 },
{ eng: "River", cantonese: "河 (ho4)", level: 26 },
{ eng: "Lake", cantonese: "湖 (wu4)", level: 26 },
{ eng: "Bridge", cantonese: "橋 (kiu4)", level: 26 },

// L27: Health & Medical
{ eng: "Fever", cantonese: "發燒 (faat3 siu1)", level: 27 },
{ eng: "Cough", cantonese: "咳 (kat1)", level: 27 },
{ eng: "Cold / Flu", cantonese: "感冒 (gam2 mou6)", level: 27 },
{ eng: "Pharmacy", cantonese: "藥房 (joek6 fong4)", level: 27 },
{ eng: "Pill", cantonese: "藥丸 (joek6 jyun2)", level: 27 },
{ eng: "Injection", cantonese: "打針 (daa2 zam1)", level: 27 },
{ eng: "Blood", cantonese: "血 (hyut3)", level: 27 },
{ eng: "Bandage", cantonese: "膠布 (gaau1 bou3)", level: 27 },
{ eng: "Emergency", cantonese: "緊急 (gan2 gap1)", level: 27 },
{ eng: "Ambulance", cantonese: "救護車 (gau3 wu6 ce1)", level: 27 },
{ eng: "Allergy", cantonese: "敏感 (man5 gam2)", level: 27 },
{ eng: "Symptom", cantonese: "病徵 (beng6 zing1)", level: 27 },
{ eng: "Recover", cantonese: "好返 (hou2 faan1)", level: 27 },
{ eng: "Healthy", cantonese: "健康 (gin6 hong1)", level: 27 },
{ eng: "Diet", cantonese: "節食 (zit3 sik6)", level: 27 },

// L28: Arts & Entertainment
{ eng: "Art", cantonese: "藝術 (ngai6 seot6)", level: 28 },
{ eng: "Painting", cantonese: "畫 (waa2)", level: 28 },
{ eng: "Draw", cantonese: "畫畫 (waa6 waa2)", level: 28 },
{ eng: "Dance", cantonese: "跳舞 (tiu3 mou5)", level: 28 },
{ eng: "Theater", cantonese: "劇院 (kek6 jyun2)", level: 28 },
{ eng: "Concert", cantonese: "演唱會 (jin2 coeng3 wui2)", level: 28 },
{ eng: "Instrument", cantonese: "樂器 (ngok6 hei3)", level: 28 },
{ eng: "Guitar", cantonese: "結他 (git3 taa1)", level: 28 },
{ eng: "Piano", cantonese: "鋼琴 (gong3 kam4)", level: 28 },
{ eng: "Novel", cantonese: "小說 (siu2 syut3)", level: 28 },
{ eng: "Poem", cantonese: "詩 (si1)", level: 28 },
{ eng: "Museum", cantonese: "博物館 (bok3 mat6 gun2)", level: 28 },
{ eng: "Exhibition", cantonese: "展覽 (zin2 laam2)", level: 28 },
{ eng: "Audience", cantonese: "觀眾 (gun1 zung3)", level: 28 },
{ eng: "Magic", cantonese: "魔術 (mo1 seot6)", level: 28 },

// L29: Politics & Society
{ eng: "Government", cantonese: "政府 (zing3 fu2)", level: 29 },
{ eng: "Law", cantonese: "法律 (faat3 leot6)", level: 29 },
{ eng: "Rule", cantonese: "規則 (kwai1 zak1)", level: 29 },
{ eng: "Vote", cantonese: "投票 (tau4 piu3)", level: 29 },
{ eng: "President", cantonese: "總統 (zung2 tung2)", level: 29 },
{ eng: "Politician", cantonese: "政客 (zing3 haak3)", level: 29 },
{ eng: "Election", cantonese: "選舉 (syun2 geoi2)", level: 29 },
{ eng: "War", cantonese: "戰爭 (zin3 zang1)", level: 29 },
{ eng: "Peace", cantonese: "和平 (wo4 ping4)", level: 29 },
{ eng: "Army", cantonese: "軍隊 (gwan1 deoi2)", level: 29 },
{ eng: "Crime", cantonese: "罪案 (zeoi6 on3)", level: 29 },
{ eng: "Prison", cantonese: "監獄 (gaam1 juk6)", level: 29 },
{ eng: "Judge", cantonese: "法官 (faat3 gun1)", level: 29 },
{ eng: "Rights", cantonese: "權利 (kyun4 lei6)", level: 29 },
{ eng: "Citizen", cantonese: "公民 (gung1 man4)", level: 29 },

// L30: Household Chores & Tools
{ eng: "Sweep", cantonese: "掃地 (sou3 dei6)", level: 30 },
{ eng: "Mop", cantonese: "拖地 (to1 dei6)", level: 30 },
{ eng: "Vacuum", cantonese: "吸塵 (kap1 can4)", level: 30 },
{ eng: "Trash", cantonese: "垃圾 (laap6 saap3)", level: 30 },
{ eng: "Dust", cantonese: "塵 (can4)", level: 30 },
{ eng: "Tool", cantonese: "工具 (gung1 geoi6)", level: 30 },
{ eng: "Hammer", cantonese: "鎚仔 (ceoi4 zai2)", level: 30 },
{ eng: "Nail", cantonese: "釘 (deng1)", level: 30 },
{ eng: "Scissors", cantonese: "鉸剪 (gaau3 zin2)", level: 30 },
{ eng: "Knife", cantonese: "刀 (dou1)", level: 30 },
{ eng: "Spoon", cantonese: "匙羹 (ci4 gang1)", level: 30 },
{ eng: "Fork", cantonese: "叉 (caa1)", level: 30 },
{ eng: "Chopsticks", cantonese: "筷子 (faai3 zi2)", level: 30 },
{ eng: "Bowl", cantonese: "碗 (wun2)", level: 30 },
{ eng: "Plate", cantonese: "碟 (dip6)", level: 30 },

// L31: Tourism & Sightseeing (Tourist Tier Starts)
{ eng: "Tourist", cantonese: "遊客 (jau4 haak3)", level: 31 },
{ eng: "Travel", cantonese: "旅行 (leoi5 hang4)", level: 31 },
{ eng: "Tour Guide", cantonese: "導遊 (dou6 jau4)", level: 31 },
{ eng: "Souvenir", cantonese: "手信 (sau2 seon3)", level: 31 },
{ eng: "Postcard", cantonese: "明信片 (ming4 seon3 pin2)", level: 31 },
{ eng: "Stamp", cantonese: "郵票 (jau4 piu3)", level: 31 },
{ eng: "Sightseeing", cantonese: "觀光 (gun1 gwong1)", level: 31 },
{ eng: "Scenery", cantonese: "風景 (fung1 ging2)", level: 31 },
{ eng: "Temple", cantonese: "廟 (miu2)", level: 31 },
{ eng: "Monument", cantonese: "紀念碑 (gei3 nin6 bei1)", level: 31 },
{ eng: "Castle", cantonese: "城堡 (sing4 bou2)", level: 31 },
{ eng: "Palace", cantonese: "皇宮 (wong4 gung1)", level: 31 },
{ eng: "Zoo", cantonese: "動物園 (dung6 mat6 jyun4)", level: 31 },
{ eng: "Theme Park", cantonese: "主題公園 (zyu2 tai4 gung1 jyun2)", level: 31 },
{ eng: "Lost (lose way)", cantonese: "迷路 (mai4 lou6)", level: 31 },

// L32: Transportation & Directions II
{ eng: "Intersection", cantonese: "十字路口 (sap6 zi6 lou6 hau2)", level: 32 },
{ eng: "Traffic Light", cantonese: "紅綠燈 (hung4 luk6 dang1)", level: 32 },
{ eng: "Highway", cantonese: "高速公路 (gou1 cuk1 gung1 lou6)", level: 32 },
{ eng: "Tunnel", cantonese: "隧道 (seoi6 dou6)", level: 32 },
{ eng: "Ferry", cantonese: "渡輪 (dou6 leon4)", level: 32 },
{ eng: "Cruise", cantonese: "郵輪 (jau4 leon4)", level: 32 },
{ eng: "Rent a car", cantonese: "租車 (zou1 ce1)", level: 32 },
{ eng: "Bicycle", cantonese: "單車 (daan1 ce1)", level: 32 },
{ eng: "Subway Station", cantonese: "地鐵站 (dei6 tit3 zaam6)", level: 32 },
{ eng: "Bus Stop", cantonese: "巴士站 (baa1 si2 zaam6)", level: 32 },
{ eng: "Platform", cantonese: "月台 (jyut6 toi4)", level: 32 },
{ eng: "Ticket Office", cantonese: "售票處 (sau6 piu3 cyu3)", level: 32 },
{ eng: "Seat", cantonese: "位 (wai2)", level: 32 },
{ eng: "Passenger", cantonese: "乘客 (sing4 haak3)", level: 32 },
{ eng: "Depart", cantonese: "出發 (ceot1 faat3)", level: 32 },

// L33: Accommodation & Hotel
{ eng: "Reception", cantonese: "接待處 (zip3 doi6 cyu3)", level: 33 },
{ eng: "Lobby", cantonese: "大堂 (daai6 tong4)", level: 33 },
{ eng: "Elevator", cantonese: "𨋢 (lip1)", level: 33 },
{ eng: "Stairs", cantonese: "樓梯 (lau4 tai1)", level: 33 },
{ eng: "Single Room", cantonese: "單人房 (daan1 jan4 fong2)", level: 33 },
{ eng: "Double Room", cantonese: "雙人房 (soeng1 jan4 fong2)", level: 33 },
{ eng: "Towel", cantonese: "毛巾 (mou4 gan1)", level: 33 },
{ eng: "Soap", cantonese: "番梘 (faan1 gaan2)", level: 33 },
{ eng: "Shampoo", cantonese: "洗頭水 (sai2 tau4 seoi2)", level: 33 },
{ eng: "Toothbrush", cantonese: "牙刷 (ngaa4 caat3)", level: 33 },
{ eng: "Toothpaste", cantonese: "牙膏 (ngaa4 gou1)", level: 33 },
{ eng: "Toilet Paper", cantonese: "廁紙 (ci3 zi2)", level: 33 },
{ eng: "Air Conditioning", cantonese: "冷氣 (laang5 hei3)", level: 33 },
{ eng: "Heater", cantonese: "暖爐 (nyun5 lou4)", level: 33 },
{ eng: "Blanket", cantonese: "被 (pei5)", level: 33 },

// L34: Shopping & Money II
{ eng: "Shopping Mall", cantonese: "商場 (soeng1 coeng4)", level: 34 },
{ eng: "Night Market", cantonese: "夜市 (je6 si5)", level: 34 },
{ eng: "Fitting Room", cantonese: "試身室 (si3 san1 sat1)", level: 34 },
{ eng: "Size", cantonese: "碼 (maa5)", level: 34 },
{ eng: "Try on", cantonese: "試 (si3)", level: 34 },
{ eng: "Too Expensive", cantonese: "太貴 (taai3 gwai3)", level: 34 },
{ eng: "Cheaper (bargain)", cantonese: "平啲 (peng4 di1)", level: 34 },
{ eng: "Sold Out", cantonese: "賣晒 (maai6 saai3)", level: 34 },
{ eng: "Cashier", cantonese: "收銀處 (sau1 ngan4 cyu3)", level: 34 },
{ eng: "Plastic Bag", cantonese: "膠袋 (gaau1 doi2)", level: 34 },
{ eng: "Change / Coins", cantonese: "散紙 (saan2 zi2)", level: 34 },
{ eng: "Banknote", cantonese: "紙幣 (zi2 bai6)", level: 34 },
{ eng: "ATM", cantonese: "櫃員機 (gwai6 jyun4 gei1)", level: 34 },
{ eng: "Brand", cantonese: "牌子 (paai4 zi2)", level: 34 },
{ eng: "Quality", cantonese: "質素 (zat1 sou3)", level: 34 },

// L35: Dining Out & Menus
{ eng: "Menu", cantonese: "餐牌 (caan1 paai4)", level: 35 },
{ eng: "Order food", cantonese: "叫嘢食 (giu3 je5 sik6)", level: 35 },
{ eng: "Bill / Check", cantonese: "埋單 (maai4 daan1)", level: 35 },
{ eng: "Tip", cantonese: "貼士 (tip1 si2)", level: 35 },
{ eng: "Buffet", cantonese: "自助餐 (zi6 zo6 caan1)", level: 35 },
{ eng: "Spicy", cantonese: "辣 (laat6)", level: 35 },
{ eng: "Sweet", cantonese: "甜 (tim4)", level: 35 },
{ eng: "Sour", cantonese: "酸 (syun1)", level: 35 },
{ eng: "Salty", cantonese: "鹹 (haam4)", level: 35 },
{ eng: "Bitter", cantonese: "苦 (fu2)", level: 35 },
{ eng: "Vegetarian", cantonese: "齋 (zaai1)", level: 35 },
{ eng: "Seafood", cantonese: "海鮮 (hoi2 sin1)", level: 35 },
{ eng: "Dessert", cantonese: "甜品 (tim4 ban2)", level: 35 },
{ eng: "Napkin", cantonese: "紙巾 (zi2 gan1)", level: 35 },
{ eng: "Ice", cantonese: "冰 (bing1)", level: 35 },

// L36: Emergencies & Problems
{ eng: "Help!", cantonese: "救命! (gau3 ming6!)", level: 36 },
{ eng: "Police Station", cantonese: "警署 (ging2 cyu5)", level: 36 },
{ eng: "Steal", cantonese: "偷 (tau1)", level: 36 },
{ eng: "Lose (something)", cantonese: "唔見咗 (m4 gin3 zo2)", level: 36 },
{ eng: "Fire (emergency)", cantonese: "火燭 (fo2 zuk1)", level: 36 },
{ eng: "Danger", cantonese: "危險 (ngai4 him2)", level: 36 },
{ eng: "Safe", cantonese: "安全 (on1 cyun4)", level: 36 },
{ eng: "Accident", cantonese: "意外 (ji3 ngoi6)", level: 36 },
{ eng: "Sick / Ill", cantonese: "唔舒服 (m4 syu1 fuk6)", level: 36 },
{ eng: "Clinic", cantonese: "診所 (can2 so2)", level: 36 },
{ eng: "Painkiller", cantonese: "止痛藥 (zi2 tung3 joek6)", level: 36 },
{ eng: "Diarrhea", cantonese: "肚屙 (tou5 o1)", level: 36 },
{ eng: "Embassy", cantonese: "大使館 (daai6 si3 gun2)", level: 36 },
{ eng: "Translation", cantonese: "翻譯 (faan1 jik6)", level: 36 },
{ eng: "Understand", cantonese: "明白 (ming4 baak6)", level: 36 },

// L37: Weather Details & Seasons
{ eng: "Spring", cantonese: "春天 (ceon1 tin1)", level: 37 },
{ eng: "Summer", cantonese: "夏天 (haa6 tin1)", level: 37 },
{ eng: "Autumn", cantonese: "秋天 (cau1 tin1)", level: 37 },
{ eng: "Winter", cantonese: "冬天 (dung1 tin1)", level: 37 },
{ eng: "Raincoat", cantonese: "雨褸 (jyu5 lau1)", level: 37 },
{ eng: "Typhoon", cantonese: "颱風 (toi4 fung1)", level: 37 },
{ eng: "Temperature", cantonese: "溫度 (wan1 dou6)", level: 37 },
{ eng: "Degree", cantonese: "度 (dou6)", level: 37 },
{ eng: "Humid", cantonese: "濕 (sap1)", level: 37 },
{ eng: "Dry", cantonese: "乾 (gon1)", level: 37 },
{ eng: "Storm", cantonese: "暴風雨 (bou6 fung1 jyu5)", level: 37 },
{ eng: "Sunny", cantonese: "好天 (hou2 tin1)", level: 37 },
{ eng: "Cloudy", cantonese: "多雲 (do1 wan4)", level: 37 },
{ eng: "Fog", cantonese: "霧 (mou6)", level: 37 },
{ eng: "Thunder", cantonese: "雷 (leoi4)", level: 37 },

// L38: Interacting with Locals
{ eng: "Excuse me (passing by)", cantonese: "借借 (ze3 ze3)", level: 38 },
{ eng: "Sorry", cantonese: "對唔住 (deoi3 m4 zyu6)", level: 38 },
{ eng: "Speak slower", cantonese: "講慢啲 (gong2 maan6 di1)", level: 38 },
{ eng: "Say again", cantonese: "講多次 (gong2 do1 ci3)", level: 38 },
{ eng: "How much?", cantonese: "幾多錢 (gei2 do1 cin4)", level: 38 },
{ eng: "What is this?", cantonese: "呢個係咩 (ni1 go3 hai6 me1)", level: 38 },
{ eng: "Where is...?", cantonese: "喺邊 (hai2 bin1)", level: 38 },
{ eng: "Can you...?", cantonese: "可唔可以 (ho2 m4 ho2 ji5)", level: 38 },
{ eng: "Take photo", cantonese: "影相 (jing2 soeng2)", level: 38 },
{ eng: "English", cantonese: "英文 (jing1 man4)", level: 38 },
{ eng: "Cantonese", cantonese: "廣東話 (gwong2 dung1 waa6)", level: 38 },
{ eng: "Foreigner", cantonese: "外國人 (ngoi6 gwok3 jan4)", level: 38 },
{ eng: "Local", cantonese: "本地人 (bun2 dei6 jan4)", level: 38 },
{ eng: "Culture", cantonese: "文化 (man4 faa3)", level: 38 },
{ eng: "Tasty / Good flavor", cantonese: "好味 (hou2 mei6)", level: 38 },

// L39: Leisure & Activities
{ eng: "Bar", cantonese: "酒吧 (zau2 baa1)", level: 39 },
{ eng: "Karaoke", cantonese: "唱K (coeng3 K)", level: 39 },
{ eng: "Casino", cantonese: "賭場 (dou2 coeng4)", level: 39 },
{ eng: "Gym", cantonese: "健身室 (gin6 san1 sat1)", level: 39 },
{ eng: "Yoga", cantonese: "瑜伽 (jyu4 gaa1)", level: 39 },
{ eng: "Swimming Pool", cantonese: "泳池 (wing6 ci4)", level: 39 },
{ eng: "Coast", cantonese: "海岸 (hoi2 ngon6)", level: 39 },
{ eng: "Spa", cantonese: "水療 (seoi2 liu4)", level: 39 },
{ eng: "Massage", cantonese: "按摩 (on3 mo1)", level: 39 },
{ eng: "Sauna", cantonese: "桑拿 (song1 naa4)", level: 39 },
{ eng: "Picnic", cantonese: "野餐 (je5 caan1)", level: 39 },
{ eng: "Camp", cantonese: "露營 (lou6 jing4)", level: 39 },
{ eng: "Hike", cantonese: "行山 (haang4 saan1)", level: 39 },
{ eng: "Theme", cantonese: "主題 (zyu2 tai4)", level: 39 },
{ eng: "Event", cantonese: "活動 (wut6 dung6)", level: 39 },

// L40: Travel Logistics (Tourist Tier Ends)
{ eng: "Memory", cantonese: "回憶 (wui4 jik1)", level: 40 },
{ eng: "View", cantonese: "景 (ging2)", level: 40 },
{ eng: "Sunrise", cantonese: "日出 (jat6 ceot1)", level: 40 },
{ eng: "Sunset", cantonese: "日落 (jat6 lok6)", level: 40 },
{ eng: "Star", cantonese: "星 (sing1)", level: 40 },
{ eng: "Relax", cantonese: "放鬆 (fong3 sung1)", level: 40 },
{ eng: "Jetlag", cantonese: "時差 (si4 caa1)", level: 40 },
{ eng: "Schedule", cantonese: "行程 (haang4 cing4)", level: 40 },
{ eng: "Book / Reserve", cantonese: "預訂 (jyu6 ding6)", level: 40 },
{ eng: "Cancel", cantonese: "取消 (ceoi2 siu1)", level: 40 },
{ eng: "Confirm", cantonese: "確認 (kok3 jing6)", level: 40 },
{ eng: "Delay", cantonese: "延遲 (jin4 ci4)", level: 40 },
{ eng: "Direct flight", cantonese: "直航 (zik6 hong4)", level: 40 },
{ eng: "Transfer flight", cantonese: "轉機 (zyun3 gei1)", level: 40 },
{ eng: "Terminal", cantonese: "客運大樓 (haak3 wan6 daai6 lau4)", level: 40 },

// L41: Toys & Playground (Child Tier Starts)
{ eng: "Toy", cantonese: "玩具 (waan6 geoi6)", level: 41 },
{ eng: "Doll / Stuffed Animal", cantonese: "公仔 (gung1 zai2)", level: 41 },
{ eng: "Ball", cantonese: "波 (bo1)", level: 41 },
{ eng: "Kite", cantonese: "紙鳶 (zi2 jyun2)", level: 41 },
{ eng: "Balloon", cantonese: "氣球 (hei3 kau4)", level: 41 },
{ eng: "Playground", cantonese: "遊樂場 (jau4 lok6 coeng4)", level: 41 },
{ eng: "Slide", cantonese: "滑梯 (waat6 tai1)", level: 41 },
{ eng: "Swing", cantonese: "千秋 (cin1 cau1)", level: 41 },
{ eng: "Seesaw", cantonese: "搖搖板 (jiu4 jiu4 baan2)", level: 41 },
{ eng: "Hide and seek", cantonese: "捉迷藏 (zuk1 mai4 cong4)", level: 41 },
{ eng: "Sandbox", cantonese: "沙池 (saa1 ci4)", level: 41 },
{ eng: "Jump rope", cantonese: "跳繩 (tiu3 sing2)", level: 41 },
{ eng: "Building Blocks", cantonese: "積木 (zik1 muk6)", level: 41 },
{ eng: "Puzzle", cantonese: "拼圖 (ping3 tou4)", level: 41 },
{ eng: "Coloring", cantonese: "填色 (tin4 sik1)", level: 41 },

// L42: Kindergarten & Play
{ eng: "Kindergarten", cantonese: "幼稚園 (jau3 zi6 jyun2)", level: 42 },
{ eng: "Alphabet", cantonese: "字母 (zi6 mou5)", level: 42 },
{ eng: "Vocabulary", cantonese: "生字 (saang1 zi6)", level: 42 },
{ eng: "Story", cantonese: "故事 (gu3 si6)", level: 42 },
{ eng: "Fairy tale", cantonese: "童話 (tung4 waa6)", level: 42 },
{ eng: "Nursery rhyme", cantonese: "兒歌 (ji4 go1)", level: 42 },
{ eng: "Learn", cantonese: "學習 (hok6 zaap6)", level: 42 },
{ eng: "Ask", cantonese: "問 (man6)", level: 42 },
{ eng: "Answer", cantonese: "答 (daap3)", level: 42 },
{ eng: "Borrow", cantonese: "借 (ze3)", level: 42 },
{ eng: "Return (item)", cantonese: "還 (waan4)", level: 42 },
{ eng: "Lunchbox", cantonese: "飯盒 (faan6 hap2)", level: 42 },
{ eng: "Snack", cantonese: "小食 (siu2 sik6)", level: 42 },
{ eng: "Candy", cantonese: "糖果 (tong4 gwo2)", level: 42 },
{ eng: "Chocolate", cantonese: "朱古力 (zyu1 gu1 lik1)", level: 42 },

// L43: Behavior & Emotions (Child)
{ eng: "Cry", cantonese: "喊 (haam3)", level: 43 },
{ eng: "Laugh", cantonese: "笑 (siu3)", level: 43 },
{ eng: "Smile", cantonese: "微笑 (mei4 siu3)", level: 43 },
{ eng: "Scared", cantonese: "驚 (geng1)", level: 43 },
{ eng: "Surprised", cantonese: "嚇親 (haak3 can1)", level: 43 },
{ eng: "Shy", cantonese: "怕醜 (paa3 cau2)", level: 43 },
{ eng: "Brave", cantonese: "勇敢 (jung5 gam2)", level: 43 },
{ eng: "Naughty", cantonese: "曳 (jai5)", level: 43 },
{ eng: "Good / Obedient", cantonese: "乖 (gwaai1)", level: 43 },
{ eng: "Smart", cantonese: "叻 (lek1)", level: 43 },
{ eng: "Stupid / Silly", cantonese: "蠢 (ceon2)", level: 43 },
{ eng: "Loud", cantonese: "嘈 (cou4)", level: 43 },
{ eng: "Quiet", cantonese: "靜 (zing6)", level: 43 },
{ eng: "Messy", cantonese: "亂 (lyun6)", level: 43 },
{ eng: "Clean / Tidy", cantonese: "乾淨 (gon1 zing6)", level: 43 },

// L44: Bedtime & Routines
{ eng: "Bedtime", cantonese: "瞓覺時間 (fan3 gaau3 si4 gaan3)", level: 44 },
{ eng: "Pajamas", cantonese: "睡衣 (seoi6 ji1)", level: 44 },
{ eng: "Pillow", cantonese: "枕頭 (zam2 tau4)", level: 44 },
{ eng: "Dream", cantonese: "發夢 (faat3 mung6)", level: 44 },
{ eng: "Nightmare", cantonese: "發噩夢 (faat3 ngok6 mung6)", level: 44 },
{ eng: "Wake up early", cantonese: "早起 (zou2 hei2)", level: 44 },
{ eng: "Wash hands", cantonese: "洗手 (sai2 sau2)", level: 44 },
{ eng: "Go to toilet", cantonese: "去廁所 (heoi3 ci3 so2)", level: 44 },
{ eng: "Bubble bath", cantonese: "泡泡浴 (pou5 pou5 juk6)", level: 44 },
{ eng: "Teddy bear", cantonese: "熊仔 (hung4 zai2)", level: 44 },
{ eng: "Storybook", cantonese: "故事書 (gu3 si6 syu1)", level: 44 },
{ eng: "Lullaby", cantonese: "搖籃曲 (jiu4 laam4 kuk1)", level: 44 },
{ eng: "Hug", cantonese: "攬 (laam5)", level: 44 },
{ eng: "Kiss", cantonese: "錫 (sek3)", level: 44 },
{ eng: "Goodnight", cantonese: "早啲唞 (zou2 di1 tau2)", level: 44 },

// L45: Small Animals & Nature
{ eng: "Puppy", cantonese: "狗仔 (gau2 zai2)", level: 45 },
{ eng: "Kitten", cantonese: "貓仔 (maau1 zai2)", level: 45 },
{ eng: "Duck", cantonese: "鴨 (aap3)", level: 45 },
{ eng: "Frog", cantonese: "青蛙 (cing1 waa1)", level: 45 },
{ eng: "Butterfly", cantonese: "蝴蝶 (wu4 dip6)", level: 45 },
{ eng: "Insect / Bug", cantonese: "蟲 (cung4)", level: 45 },
{ eng: "Spider", cantonese: "蜘蛛 (zi1 zyu1)", level: 45 },
{ eng: "Ant", cantonese: "螞蟻 (maa5 ngai5)", level: 45 },
{ eng: "Bee", cantonese: "蜜蜂 (mat6 fung1)", level: 45 },
{ eng: "Snail", cantonese: "蝸牛 (wo1 ngau4)", level: 45 },
{ eng: "Rabbit", cantonese: "兔仔 (tou3 zai2)", level: 45 },
{ eng: "Turtle", cantonese: "烏龜 (wu1 gwai1)", level: 45 },
{ eng: "Mud", cantonese: "泥漿 (nai4 zoeng1)", level: 45 },
{ eng: "Puddle", cantonese: "水氹 (seoi2 tam5)", level: 45 },
{ eng: "Rainbow", cantonese: "彩虹 (coi2 hung4)", level: 45 },

// L46: Extended Family
{ eng: "Grandpa (Paternal)", cantonese: "爺爺 (je4 je4)", level: 46 },
{ eng: "Grandma (Paternal)", cantonese: "嫲嫲 (maa4 maa4)", level: 46 },
{ eng: "Grandpa (Maternal)", cantonese: "公公 (gung1 gung1)", level: 46 },
{ eng: "Grandma (Maternal)", cantonese: "婆婆 (po4 po4)", level: 46 },
{ eng: "Uncle (Father's younger brother)", cantonese: "叔叔 (suk1 suk1)", level: 46 },
{ eng: "Aunt (Father's sister)", cantonese: "姑媽 (gu1 maa1)", level: 46 },
{ eng: "Uncle (Mother's brother)", cantonese: "舅父 (kau5 fu2)", level: 46 },
{ eng: "Aunt (Mother's sister)", cantonese: "阿姨 (aa3 ji1)", level: 46 },
{ eng: "Older Male Cousin", cantonese: "表哥 (biu2 go1)", level: 46 },
{ eng: "Younger Male Cousin", cantonese: "表弟 (biu2 dai6)", level: 46 },
{ eng: "Older Female Cousin", cantonese: "表姐 (biu2 ze1)", level: 46 },
{ eng: "Younger Female Cousin", cantonese: "表妹 (biu2 mui6)", level: 46 },
{ eng: "Baby", cantonese: "BB (bi4 bi1)", level: 46 },
{ eng: "Twins", cantonese: "雙胞胎 (soeng1 baau1 toi1)", level: 46 },
{ eng: "Family", cantonese: "屋企人 (uk1 kei2 jan4)", level: 46 },

// L47: Kids Clothing & Gear
{ eng: "Sweater", cantonese: "冷衫 (laang1 saam1)", level: 47 },
{ eng: "Shorts", cantonese: "短褲 (dyun2 fu3)", level: 47 },
{ eng: "Underwear", cantonese: "底褲 (dai2 fu3)", level: 47 },
{ eng: "Diaper", cantonese: "片 (pin2)", level: 47 },
{ eng: "Bib", cantonese: "口水肩 (hau2 seoi2 gin1)", level: 47 },
{ eng: "Boots", cantonese: "靴 (hoe1)", level: 47 },
{ eng: "Sneakers", cantonese: "波鞋 (bo1 haai4)", level: 47 },
{ eng: "Slippers", cantonese: "拖鞋 (to1 haai4)", level: 47 },
{ eng: "Gloves / Mittens", cantonese: "手套 (sau2 tou3)", level: 47 },
{ eng: "Scarf", cantonese: "頸巾 (geng2 gan1)", level: 47 },
{ eng: "Zipper", cantonese: "拉鏈 (laai1 lin2)", level: 47 },
{ eng: "Pocket", cantonese: "袋 (doi2)", level: 47 },
{ eng: "Button (clothes)", cantonese: "鈕 (nau2)", level: 47 },
{ eng: "Backpack", cantonese: "書包 (syu1 baau1)", level: 47 },
{ eng: "Water Bottle", cantonese: "水樽 (seoi2 zeon1)", level: 47 },

// L48: Arts, Crafts & School
{ eng: "Pencil", cantonese: "鉛筆 (jyun4 bat1)", level: 48 },
{ eng: "Crayon", cantonese: "蠟筆 (laap6 bat1)", level: 48 },
{ eng: "Eraser", cantonese: "擦膠 (caat3 gaau1)", level: 48 },
{ eng: "Ruler", cantonese: "間尺 (gaan3 cek3)", level: 48 },
{ eng: "Glue", cantonese: "膠水 (gaau1 seoi2)", level: 48 },
{ eng: "Tape", cantonese: "膠紙 (gaau1 zi2)", level: 48 },
{ eng: "Notebook", cantonese: "筆記簿 (bat1 gei3 bou2)", level: 48 },
{ eng: "Coloring", cantonese: "填色 (tin4 sik1)", level: 48 },
{ eng: "Playdough / Clay", cantonese: "泥膠 (nai4 gaau1)", level: 48 },
{ eng: "Sticker", cantonese: "貼紙 (tip3 zi2)", level: 48 },
{ eng: "Stamp (toy)", cantonese: "印仔 (jan3 zai2)", level: 48 },
{ eng: "Paint", cantonese: "顏料 (ngaan4 liu4)", level: 48 },
{ eng: "Paintbrush", cantonese: "畫筆 (waa6 bat1)", level: 48 },
{ eng: "Origami", cantonese: "摺紙 (zip3 zi2)", level: 48 },
{ eng: "Craft", cantonese: "手工 (sau2 gung1)", level: 48 },

// L49: Birthday & Party
{ eng: "Party", cantonese: "派對 (paai3 deoi3)", level: 49 },
{ eng: "Gift / Present", cantonese: "禮物 (lai5 mat6)", level: 49 },
{ eng: "Ribbon", cantonese: "絲帶 (si1 daai3)", level: 49 },
{ eng: "Greeting Card", cantonese: "賀卡 (ho6 kaat1)", level: 49 },
{ eng: "Birthday Cake", cantonese: "生日蛋糕 (saang1 jat6 daan6 gou1)", level: 49 },
{ eng: "Candle", cantonese: "蠟燭 (laap6 zuk1)", level: 49 },
{ eng: "Blow", cantonese: "吹 (ceoi1)", level: 49 },
{ eng: "Make a wish", cantonese: "許願 (heoi2 jyun6)", level: 49 },
{ eng: "Surprise", cantonese: "驚喜 (ging1 hei2)", level: 49 },
{ eng: "Guest", cantonese: "客人 (haak3 jan4)", level: 49 },
{ eng: "Prize", cantonese: "獎品 (zoeng2 ban2)", level: 49 },
{ eng: "Clown", cantonese: "小丑 (siu2 cau2)", level: 49 },
{ eng: "Fun", cantonese: "好玩 (hou2 waan2)", level: 49 },
{ eng: "Celebrate", cantonese: "慶祝 (hing3 zuk1)", level: 49 },
{ eng: "Snacks", cantonese: "零食 (ling4 sik6)", level: 49 },

// L50: Little Phrases & Exclamations (Child Tier Ends)
{ eng: "Mine", cantonese: "我嘅 (ngo5 ge3)", level: 50 },
{ eng: "Yours", cantonese: "你嘅 (nei5 ge3)", level: 50 },
{ eng: "Together", cantonese: "一齊 (jat1 cai4)", level: 50 },
{ eng: "Let's play", cantonese: "一齊玩 (jat1 cai4 waan2)", level: 50 },
{ eng: "My turn", cantonese: "到我 (dou3 ngo5)", level: 50 },
{ eng: "Your turn", cantonese: "到你 (dou3 nei5)", level: 50 },
{ eng: "Stop", cantonese: "停 (ting4)", level: 50 },
{ eng: "Be careful", cantonese: "小心 (siu2 sam1)", level: 50 },
{ eng: "Wait a minute", cantonese: "等陣 (dang2 zan6)", level: 50 },
{ eng: "Help me", cantonese: "幫我 (bong1 ngo5)", level: 50 },
{ eng: "I want", cantonese: "我要 (ngo5 jiu3)", level: 50 },
{ eng: "I don't want", cantonese: "我唔要 (ngo5 m4 jiu3)", level: 50 },
{ eng: "It hurts", cantonese: "好痛 (hou2 tung3)", level: 50 },
{ eng: "It's itchy", cantonese: "好痕 (hou2 han4)", level: 50 },
{ eng: "Very smart / Awesome", cantonese: "好叻 (hou2 lek1)", level: 50 },

// L51: School Subjects & Classes (Elementary Tier Starts)
{ eng: "Math", cantonese: "數學 (sou3 hok6)", level: 51 },
{ eng: "English Class", cantonese: "英文堂 (jing1 man4 tong4)", level: 51 },
{ eng: "Chinese Class", cantonese: "中文堂 (zung1 man4 tong4)", level: 51 },
{ eng: "Science", cantonese: "科學 (fo1 hok6)", level: 51 },
{ eng: "History", cantonese: "歷史 (lik6 si2)", level: 51 },
{ eng: "Art Class", cantonese: "美術堂 (mei5 seot6 tong4)", level: 51 },
{ eng: "Music Class", cantonese: "音樂堂 (jam1 ngok6 tong4)", level: 51 },
{ eng: "PE Class", cantonese: "體育堂 (tai2 juk6 tong4)", level: 51 },
{ eng: "Class / Lesson", cantonese: "堂 (tong4)", level: 51 },
{ eng: "Exam / Test", cantonese: "考試 (haau2 si3)", level: 51 },
{ eng: "Score / Grade", cantonese: "分數 (fan1 sou3)", level: 51 },
{ eng: "Pass", cantonese: "及格 (kap6 gaak3)", level: 51 },
{ eng: "Fail", cantonese: "肥佬 (fei4 lou2)", level: 51 },
{ eng: "Homework", cantonese: "功課 (gung1 fo3)", level: 51 },
{ eng: "Recess / Break", cantonese: "小息 (siu2 sik1)", level: 51 },

// L52: School Life & Supplies
{ eng: "Pen", cantonese: "原子筆 (jyun4 zi2 bat1)", level: 52 },
{ eng: "Textbook", cantonese: "教科書 (gaau3 fo1 syu1)", level: 52 },
{ eng: "Dictionary", cantonese: "字典 (zi6 din2)", level: 52 },
{ eng: "Whiteboard", cantonese: "白板 (baak6 baan2)", level: 52 },
{ eng: "Blackboard", cantonese: "黑板 (hak1 baan2)", level: 52 },
{ eng: "Desk", cantonese: "書枱 (syu1 toi2)", level: 52 },
{ eng: "Classroom", cantonese: "課室 (fo3 sat1)", level: 52 },
{ eng: "Principal", cantonese: "校長 (haau3 zoeng2)", level: 52 },
{ eng: "Classmate", cantonese: "同學 (tung4 hok6)", level: 52 },
{ eng: "Question", cantonese: "問題 (man6 tai4)", level: 52 },
{ eng: "Answer", cantonese: "答案 (daap3 on3)", level: 52 },
{ eng: "Understand", cantonese: "明白 (ming4 baak6)", level: 52 },
{ eng: "Don't understand", cantonese: "唔明 (m4 ming4)", level: 52 },
{ eng: "Raise hand", cantonese: "舉手 (geoi2 sau2)", level: 52 },
{ eng: "Pay attention", cantonese: "留心 (lau4 sam1)", level: 52 },

// L53: Basic Earth & Space
{ eng: "Earth", cantonese: "地球 (dei6 kau4)", level: 53 },
{ eng: "Star", cantonese: "星星 (sing1 sing1)", level: 53 },
{ eng: "Space", cantonese: "太空 (taai3 hung1)", level: 53 },
{ eng: "Planet", cantonese: "星球 (sing1 kau4)", level: 53 },
{ eng: "Ocean", cantonese: "海洋 (hoi2 joeng4)", level: 53 },
{ eng: "Continent", cantonese: "大陸 (daai6 luk6)", level: 53 },
{ eng: "Island", cantonese: "島 (dou2)", level: 53 },
{ eng: "Ice", cantonese: "冰 (bing1)", level: 53 },
{ eng: "Fire", cantonese: "火 (fo2)", level: 53 },
{ eng: "Light", cantonese: "光 (gwong1)", level: 53 },
{ eng: "Dark", cantonese: "暗 (am3)", level: 53 },
{ eng: "Shadow", cantonese: "影子 (jing2 zi2)", level: 53 },
{ eng: "Sound", cantonese: "聲音 (sing1 jam1)", level: 53 },
{ eng: "Electricity", cantonese: "電 (din6)", level: 53 },
{ eng: "Magnet", cantonese: "磁石 (ci4 sek6)", level: 53 },

// L54: Hobbies & Interests
{ eng: "Read books", cantonese: "睇書 (tai2 syu1)", level: 54 },
{ eng: "Play video games", cantonese: "打機 (daa2 gei1)", level: 54 },
{ eng: "Draw pictures", cantonese: "畫畫 (waa6 waa2)", level: 54 },
{ eng: "Sing", cantonese: "唱歌 (coeng3 go1)", level: 54 },
{ eng: "Dance", cantonese: "跳舞 (tiu3 mou5)", level: 54 },
{ eng: "Swim", cantonese: "游水 (jau4 seoi2)", level: 54 },
{ eng: "Ride bike", cantonese: "踩單車 (caai2 daan1 ce1)", level: 54 },
{ eng: "Play piano", cantonese: "彈琴 (taan4 kam4)", level: 54 },
{ eng: "Watch movie", cantonese: "睇戲 (tai2 hei3)", level: 54 },
{ eng: "Listen to music", cantonese: "聽歌 (ting1 go1)", level: 54 },
{ eng: "Take photos", cantonese: "影相 (jing2 soeng2)", level: 54 },
{ eng: "Cook", cantonese: "煮嘢食 (zyu2 je5 sik6)", level: 54 },
{ eng: "Travel", cantonese: "去旅行 (heoi3 leoi5 hang4)", level: 54 },
{ eng: "Exercise", cantonese: "做運動 (zou6 wan6 dung6)", level: 54 },
{ eng: "Collect", cantonese: "收集 (sau1 zaap6)", level: 54 },

// L55: Sports & Games
{ eng: "Basketball", cantonese: "籃球 (laam4 kau4)", level: 55 },
{ eng: "Football / Soccer", cantonese: "足球 (zuk1 kau4)", level: 55 },
{ eng: "Tennis", cantonese: "網球 (mong5 kau4)", level: 55 },
{ eng: "Badminton", cantonese: "羽毛球 (jyu5 mou4 kau4)", level: 55 },
{ eng: "Ping Pong", cantonese: "乒乓波 (bing1 bam1 bo1)", level: 55 },
{ eng: "Baseball", cantonese: "棒球 (paang5 kau4)", level: 55 },
{ eng: "Swimming", cantonese: "游水 (jau4 seoi2)", level: 55 },
{ eng: "Running", cantonese: "跑步 (paau2 bou6)", level: 55 },
{ eng: "Team", cantonese: "隊 (deoi2)", level: 55 },
{ eng: "Win", cantonese: "贏 (jeng4)", level: 55 },
{ eng: "Lose", cantonese: "輸 (syu1)", level: 55 },
{ eng: "Tie / Draw", cantonese: "打和 (daa2 wo4)", level: 55 },
{ eng: "Match / Game", cantonese: "比賽 (bei2 coi3)", level: 55 },
{ eng: "Champion", cantonese: "冠軍 (gun3 gwan1)", level: 55 },
{ eng: "Coach", cantonese: "教練 (gaau3 lin6)", level: 55 },

// L56: Food & Condiments II
{ eng: "Butter", cantonese: "牛油 (ngau4 jau4)", level: 56 },
{ eng: "Cheese", cantonese: "芝士 (zi1 si2)", level: 56 },
{ eng: "Soy Sauce", cantonese: "豉油 (si6 jau4)", level: 56 },
{ eng: "Oil", cantonese: "油 (jau4)", level: 56 },
{ eng: "Vinegar", cantonese: "醋 (cou3)", level: 56 },
{ eng: "Pepper", cantonese: "胡椒 (wu4 ziu1)", level: 56 },
{ eng: "Garlic", cantonese: "蒜頭 (syun3 tau4)", level: 56 },
{ eng: "Ginger", cantonese: "薑 (goeng1)", level: 56 },
{ eng: "Onion", cantonese: "洋蔥 (joeng4 cung1)", level: 56 },
{ eng: "Tomato", cantonese: "番茄 (faan1 ke2)", level: 56 },
{ eng: "Potato", cantonese: "薯仔 (syu4 zai2)", level: 56 },
{ eng: "Carrot", cantonese: "紅蘿蔔 (hung4 lo4 baak6)", level: 56 },
{ eng: "Mushroom", cantonese: "蘑菇 (mo4 gu1)", level: 56 },
{ eng: "Salad", cantonese: "沙律 (saa1 leot2)", level: 56 },
{ eng: "Sandwich", cantonese: "三文治 (saam1 man4 zi6)", level: 56 },

// L57: Around the House II
{ eng: "Roof", cantonese: "屋頂 (uk1 deng2)", level: 57 },
{ eng: "Wall", cantonese: "牆 (coeng4)", level: 57 },
{ eng: "Floor", cantonese: "地板 (dei6 baan2)", level: 57 },
{ eng: "Ceiling", cantonese: "天花板 (tin1 faa1 baan2)", level: 57 },
{ eng: "Balcony", cantonese: "露台 (lou6 toi4)", level: 57 },
{ eng: "Stairs", cantonese: "樓梯 (lau4 tai1)", level: 57 },
{ eng: "Garage", cantonese: "車房 (ce1 fong4)", level: 57 },
{ eng: "Garden", cantonese: "花園 (faa1 jyun4)", level: 57 },
{ eng: "Fence", cantonese: "圍欄 (wai4 laan4)", level: 57 },
{ eng: "Bell", cantonese: "鐘 (zung1)", level: 57 },
{ eng: "Lock", cantonese: "鎖 (so2)", level: 57 },
{ eng: "Key", cantonese: "鎖匙 (so2 si4)", level: 57 },
{ eng: "Mailbox", cantonese: "信箱 (seon3 soeng1)", level: 57 },
{ eng: "Trash can", cantonese: "垃圾桶 (laap6 saap3 tung2)", level: 57 },
{ eng: "Broom", cantonese: "掃把 (sou3 baa2)", level: 57 },

// L58: Daily Items & Toiletries
{ eng: "Toilet", cantonese: "馬桶 (maa5 tung2)", level: 58 },
{ eng: "Sink", cantonese: "洗手盆 (sai2 sau2 pun4)", level: 58 },
{ eng: "Mirror", cantonese: "鏡 (geng3)", level: 58 },
{ eng: "Comb", cantonese: "梳 (so1)", level: 58 },
{ eng: "Hairdryer", cantonese: "風筒 (fung1 tung2)", level: 58 },
{ eng: "Toilet Paper", cantonese: "廁紙 (ci3 zi2)", level: 58 },
{ eng: "Tissue", cantonese: "紙巾 (zi2 gan1)", level: 58 },
{ eng: "Soap", cantonese: "番梘 (faan1 gaan2)", level: 58 },
{ eng: "Toothbrush", cantonese: "牙刷 (ngaa4 caat3)", level: 58 },
{ eng: "Toothpaste", cantonese: "牙膏 (ngaa4 gou1)", level: 58 },
{ eng: "Towel", cantonese: "毛巾 (mou4 gan1)", level: 58 },
{ eng: "Shampoo", cantonese: "洗頭水 (sai2 tau4 seoi2)", level: 58 },
{ eng: "Body Wash", cantonese: "沐浴露 (muk6 juk6 lou6)", level: 58 },
{ eng: "Lotion", cantonese: "潤膚露 (jeon6 fu1 lou6)", level: 58 },
{ eng: "Perfume", cantonese: "香水 (hoeng1 seoi2)", level: 58 },

// L59: City & Buildings (Elementary)
{ eng: "Building", cantonese: "建築物 (gin3 zuk1 mat6)", level: 59 },
{ eng: "Apartment", cantonese: "公寓 (gung1 jyu6)", level: 59 },
{ eng: "Post Office", cantonese: "郵局 (jau4 guk1)", level: 59 },
{ eng: "Fire Station", cantonese: "消防局 (siu1 fong4 guk1)", level: 59 },
{ eng: "Gas Station", cantonese: "油站 (jau4 zaam6)", level: 59 },
{ eng: "Bakery", cantonese: "麵包舖 (min6 baau1 pou3)", level: 59 },
{ eng: "Hair Salon", cantonese: "髮型屋 (faat3 jing4 uk1)", level: 59 },
{ eng: "Bookstore", cantonese: "書局 (syu1 guk1)", level: 59 },
{ eng: "Church", cantonese: "教堂 (gaau3 tong4)", level: 59 },
{ eng: "Square / Plaza", cantonese: "廣場 (gwong2 coeng4)", level: 59 },
{ eng: "Factory", cantonese: "工廠 (gung1 cong2)", level: 59 },
{ eng: "Office", cantonese: "辦公室 (baan6 gung1 sat1)", level: 59 },
{ eng: "Village", cantonese: "村 (cyun1)", level: 59 },
{ eng: "Suburbs", cantonese: "郊區 (gaau1 keoi1)", level: 59 },
{ eng: "Corner", cantonese: "轉角 (zyun3 gok3)", level: 59 },

// L60: Directions & Movement (Elementary Tier Ends)
{ eng: "Go straight", cantonese: "直行 (zik6 haang4)", level: 60 },
{ eng: "Turn left", cantonese: "轉左 (zyun3 zo2)", level: 60 },
{ eng: "Turn right", cantonese: "轉右 (zyun3 jau6)", level: 60 },
{ eng: "Cross the road", cantonese: "過馬路 (gwo3 maa5 lou6)", level: 60 },
{ eng: "Traffic jam", cantonese: "塞車 (sak1 ce1)", level: 60 },
{ eng: "Speed", cantonese: "速度 (cuk1 dou6)", level: 60 },
{ eng: "Brake", cantonese: "剎車 (saat3 ce1)", level: 60 },
{ eng: "Park (a car)", cantonese: "泊車 (paak3 ce1)", level: 60 },
{ eng: "Travel Ticket", cantonese: "車飛 (ce1 fei1)", level: 60 },
{ eng: "Get on (vehicle)", cantonese: "上車 (soeng5 ce1)", level: 60 },
{ eng: "Get off (vehicle)", cantonese: "落車 (lok6 ce1)", level: 60 },
{ eng: "Compass", cantonese: "指南針 (zi2 naam4 zam1)", level: 60 },
{ eng: "Distance", cantonese: "距離 (keoi5 lei4)", level: 60 },
{ eng: "Kilometer", cantonese: "公里 (gung1 lei5)", level: 60 },
{ eng: "Meter", cantonese: "米 (mai5)", level: 60 },

// L61: Academics & Subjects (Middle School Tier Starts)
{ eng: "Middle School", cantonese: "中學 (zung1 hok6)", level: 61 },
{ eng: "Subject", cantonese: "科目 (fo1 muk6)", level: 61 },
{ eng: "Geography", cantonese: "地理 (dei6 lei5)", level: 61 },
{ eng: "Physics", cantonese: "物理 (mat6 lei5)", level: 61 },
{ eng: "Chemistry", cantonese: "化學 (faa3 hok6)", level: 61 },
{ eng: "Biology", cantonese: "生物 (saang1 mat6)", level: 61 },
{ eng: "Literature", cantonese: "文學 (man4 hok6)", level: 61 },
{ eng: "Computer Science", cantonese: "電腦科 (din6 nou5 fo1)", level: 61 },
{ eng: "Calculator", cantonese: "計算機 (gai3 syun3 gei1)", level: 61 },
{ eng: "Experiment", cantonese: "實驗 (sat6 jim6)", level: 61 },
{ eng: "Project", cantonese: "專題研習 (zyun1 tai4 jin4 zaap6)", level: 61 },
{ eng: "Essay / Composition", cantonese: "作文 (zok3 man4)", level: 61 },
{ eng: "Presentation", cantonese: "演講 (jin2 gong2)", level: 61 },
{ eng: "Graduate", cantonese: "畢業 (bat1 jip6)", level: 61 },
{ eng: "Semester", cantonese: "學期 (hok6 kei4)", level: 61 },

// L62: Technology & Internet II
{ eng: "Smartphone", cantonese: "智能手機 (zi3 nang4 sau2 gei1)", level: 62 },
{ eng: "Laptop", cantonese: "手提電腦 (sau2 tai4 din6 nou5)", level: 62 },
{ eng: "Tablet", cantonese: "平板電腦 (ping4 baan2 din6 nou5)", level: 62 },
{ eng: "Battery", cantonese: "電池 (din6 ci4)", level: 62 },
{ eng: "Charger", cantonese: "充電器 (cung1 din6 hei3)", level: 62 },
{ eng: "Cable / Wire", cantonese: "電線 (din6 sin3)", level: 62 },
{ eng: "Network / WiFi", cantonese: "網絡 (mong5 lok3)", level: 62 },
{ eng: "Download", cantonese: "下載 (haa6 zoi3)", level: 62 },
{ eng: "Upload", cantonese: "上載 (soeng5 zoi3)", level: 62 },
{ eng: "File", cantonese: "檔案 (dong2 on3)", level: 62 },
{ eng: "Folder", cantonese: "文件夾 (man4 gin2 gaap3)", level: 62 },
{ eng: "Delete", cantonese: "刪除 (saan1 ceoi4)", level: 62 },
{ eng: "Save", cantonese: "儲存 (cyu5 cyun4)", level: 62 },
{ eng: "Search", cantonese: "搜尋 (sau2 cam4)", level: 62 },
{ eng: "Social Media", cantonese: "社交媒體 (se5 gaau1 mui4 tai2)", level: 62 },

// L63: Society & Environment
{ eng: "Environment", cantonese: "環境 (waan4 ging2)", level: 63 },
{ eng: "Pollution", cantonese: "污染 (wu1 jim5)", level: 63 },
{ eng: "Recycle", cantonese: "回收 (wui4 sau1)", level: 63 },
{ eng: "Nature", cantonese: "大自然 (daai6 zi6 jin4)", level: 63 },
{ eng: "Society", cantonese: "社會 (se5 wui2)", level: 63 },
{ eng: "Culture", cantonese: "文化 (man4 faa3)", level: 63 },
{ eng: "Tradition", cantonese: "傳統 (cyun4 tung2)", level: 63 },
{ eng: "Community", cantonese: "社區 (se5 keoi1)", level: 63 },
{ eng: "Volunteer", cantonese: "義工 (ji6 gung1)", level: 63 },
{ eng: "Charity", cantonese: "慈善 (ci4 sin6)", level: 63 },
{ eng: "Poverty", cantonese: "貧窮 (pan4 kung4)", level: 63 },
{ eng: "Equality", cantonese: "平等 (ping4 dang2)", level: 63 },
{ eng: "Justice", cantonese: "公義 (gung1 ji6)", level: 63 },
{ eng: "Freedom", cantonese: "自由 (zi6 jau4)", level: 63 },
{ eng: "Law", cantonese: "法律 (faat3 leot6)", level: 63 },

// L64: Media & Journalism
{ eng: "Magazine", cantonese: "雜誌 (zaap6 zi3)", level: 64 },
{ eng: "Newspaper", cantonese: "報紙 (bou3 zi2)", level: 64 },
{ eng: "Interview", cantonese: "訪問 (fong2 man6)", level: 64 },
{ eng: "Journalist", cantonese: "記者 (gei3 ze2)", level: 64 },
{ eng: "Article", cantonese: "文章 (man4 zoeng1)", level: 64 },
{ eng: "Advertisement", cantonese: "廣告 (gwong2 gou3)", level: 64 },
{ eng: "Podcast", cantonese: "播客 (bo3 haak3)", level: 64 },
{ eng: "Channel", cantonese: "頻道 (pan4 dou6)", level: 64 },
{ eng: "Episode", cantonese: "集 (zaap6)", level: 64 },
{ eng: "Director", cantonese: "導演 (dou6 jin2)", level: 64 },
{ eng: "Script", cantonese: "劇本 (kek6 bun2)", level: 64 },
{ eng: "Stage", cantonese: "舞台 (mou5 toi4)", level: 64 },
{ eng: "Character", cantonese: "角色 (gok3 sik1)", level: 64 },
{ eng: "Actor", cantonese: "演員 (jin2 jyun4)", level: 64 },
{ eng: "Festival", cantonese: "節日 (zit3 jat6)", level: 64 },

// L65: Teen Life & Pop Culture
{ eng: "Club / Society", cantonese: "學會 (hok6 wui2)", level: 65 },
{ eng: "Comic", cantonese: "漫畫 (maan6 waa2)", level: 65 },
{ eng: "Animation", cantonese: "動畫 (dung6 waa2)", level: 65 },
{ eng: "Skateboard", cantonese: "滑板 (waat6 baan2)", level: 65 },
{ eng: "Fashion", cantonese: "時裝 (si4 zong1)", level: 65 },
{ eng: "Trend", cantonese: "潮流 (ciu4 lau4)", level: 65 },
{ eng: "Idol", cantonese: "偶像 (ngau5 zoeng6)", level: 65 },
{ eng: "Fan", cantonese: "粉絲 (fan2 si1)", level: 65 },
{ eng: "Arcade", cantonese: "機舖 (gei1 pou3)", level: 65 },
{ eng: "Hang out", cantonese: "去街 (heoi3 gaai1)", level: 65 },
{ eng: "Part-time job", cantonese: "兼職 (gim1 zik1)", level: 65 },
{ eng: "Allowance", cantonese: "零用錢 (ling4 jung6 cin4)", level: 65 },
{ eng: "Diary", cantonese: "日記 (jat6 gei3)", level: 65 },
{ eng: "Secret", cantonese: "秘密 (bei3 mat6)", level: 65 },
{ eng: "Gossip", cantonese: "八卦 (baat3 gwaa3)", level: 65 },

// L66: Complex Emotions
{ eng: "Stress", cantonese: "壓力 (aat3 lik6)", level: 66 },
{ eng: "Confused", cantonese: "迷茫 (mai4 mong4)", level: 66 },
{ eng: "Nervous", cantonese: "緊張 (gan2 zoeng1)", level: 66 },
{ eng: "Excited", cantonese: "興奮 (hing1 fan5)", level: 66 },
{ eng: "Disappointed", cantonese: "失望 (sat1 mong6)", level: 66 },
{ eng: "Proud", cantonese: "驕傲 (giu1 ngou6)", level: 66 },
{ eng: "Jealous", cantonese: "妒忌 (dou3 gei6)", level: 66 },
{ eng: "Embarrassed", cantonese: "尷尬 (gaam1 gaai3)", level: 66 },
{ eng: "Guilty", cantonese: "內疚 (noi6 gau3)", level: 66 },
{ eng: "Lonely", cantonese: "寂寞 (zik6 mok6)", level: 66 },
{ eng: "Bored", cantonese: "悶 (mun6)", level: 66 },
{ eng: "Annoyed", cantonese: "煩 (faan4)", level: 66 },
{ eng: "Surprised", cantonese: "驚訝 (ging1 ngaa6)", level: 66 },
{ eng: "Worried", cantonese: "擔心 (daam1 sam1)", level: 66 },
{ eng: "Relieved", cantonese: "放心 (fong3 sam1)", level: 66 },

// L67: Describing Things & Traits
{ eng: "Important", cantonese: "重要 (zung6 jiu3)", level: 67 },
{ eng: "Famous", cantonese: "出名 (ceot1 meng2)", level: 67 },
{ eng: "Common", cantonese: "普通 (pou2 tung1)", level: 67 },
{ eng: "Special", cantonese: "特別 (dak6 bit6)", level: 67 },
{ eng: "Safe", cantonese: "安全 (on1 cyun4)", level: 67 },
{ eng: "Dangerous", cantonese: "危險 (ngai4 him2)", level: 67 },
{ eng: "Clear", cantonese: "清楚 (cing1 co2)", level: 67 },
{ eng: "Complex", cantonese: "複雜 (fuk1 zaap3)", level: 67 },
{ eng: "Simple", cantonese: "簡單 (gaan2 daan1)", level: 67 },
{ eng: "Strange / Weird", cantonese: "奇怪 (kei4 gwaai3)", level: 67 },
{ eng: "Funny", cantonese: "搞笑 (gaau2 siu3)", level: 67 },
{ eng: "Boring", cantonese: "沉悶 (cam4 mun6)", level: 67 },
{ eng: "Difficult", cantonese: "難 (naan4)", level: 67 },
{ eng: "Easy", cantonese: "容易 (jung4 ji6)", level: 67 },
{ eng: "Perfect", cantonese: "完美 (jyun4 mei5)", level: 67 },

// L68: Interpersonal & Conflict
{ eng: "Promise", cantonese: "承諾 (sing4 nok6)", level: 68 },
{ eng: "Rumor", cantonese: "謠言 (jiu4 jin4)", level: 68 },
{ eng: "Compromise", cantonese: "妥協 (to5 hip3)", level: 68 },
{ eng: "Argue", cantonese: "爭執 (zang1 zap1)", level: 68 },
{ eng: "Discuss", cantonese: "討論 (tou2 leon6)", level: 68 },
{ eng: "Suggest", cantonese: "建議 (gin3 ji5)", level: 68 },
{ eng: "Agree", cantonese: "贊成 (zaan3 sing4)", level: 68 },
{ eng: "Reject", cantonese: "拒絕 (keoi5 zyut6)", level: 68 },
{ eng: "Relationship", cantonese: "關係 (gwaan1 hai6)", level: 68 },
{ eng: "Trust", cantonese: "信任 (seon3 jam6)", level: 68 },
{ eng: "Betray", cantonese: "出賣 (ceot1 maai6)", level: 68 },
{ eng: "Misunderstand", cantonese: "誤會 (ng6 wui6)", level: 68 },
{ eng: "Support", cantonese: "支持 (zi1 ci4)", level: 68 },
{ eng: "Encourage", cantonese: "鼓勵 (gu2 lai6)", level: 68 },
{ eng: "Communication", cantonese: "溝通 (kau1 tung1)", level: 68 },

// L69: Future & Ambitions
{ eng: "Future", cantonese: "未來 (mei6 loi4)", level: 69 },
{ eng: "Goal", cantonese: "目標 (muk6 biu1)", level: 69 },
{ eng: "Dream (ambition)", cantonese: "理想 (lei5 soeng2)", level: 69 },
{ eng: "Plan", cantonese: "計劃 (gai3 waak6)", level: 69 },
{ eng: "Improve", cantonese: "進步 (zeon3 bou6)", level: 69 },
{ eng: "Challenge", cantonese: "挑戰 (tiu1 zin3)", level: 69 },
{ eng: "Opportunity", cantonese: "機會 (gei1 wui6)", level: 69 },
{ eng: "Achievement", cantonese: "成就 (sing4 zau6)", level: 69 },
{ eng: "Effort", cantonese: "努力 (nou5 lik6)", level: 69 },
{ eng: "Prepare", cantonese: "準備 (zeon2 bei6)", level: 69 },
{ eng: "Give up", cantonese: "放棄 (fong3 hei3)", level: 69 },
{ eng: "Hope", cantonese: "希望 (hei1 mong6)", level: 69 },
{ eng: "Expect", cantonese: "期待 (kei4 doi6)", level: 69 },
{ eng: "Decide", cantonese: "決定 (kyut3 ding6)", level: 69 },
{ eng: "Choice", cantonese: "選擇 (syun2 zaak6)", level: 69 },

// L70: Middle School Ends / Academics
{ eng: "High School", cantonese: "高中 (gou1 zung1)", level: 70 },
{ eng: "Professor", cantonese: "教授 (gaau3 sau6)", level: 70 },
{ eng: "Campus", cantonese: "校園 (haau3 jyun4)", level: 70 },
{ eng: "Scholarship", cantonese: "獎學金 (zoeng2 hok6 gam1)", level: 70 },
{ eng: "Report", cantonese: "報告 (bou3 gou3)", level: 70 },
{ eng: "Knowledge", cantonese: "知識 (zi1 sik1)", level: 70 },
{ eng: "Memory (Brain)", cantonese: "記憶力 (gei3 jik1 lik6)", level: 70 },
{ eng: "Logic", cantonese: "邏輯 (lo4 cap1)", level: 70 },
{ eng: "Research", cantonese: "研究 (jin4 gau3)", level: 70 },
{ eng: "Rule", cantonese: "規矩 (kwai1 geoi2)", level: 70 },
{ eng: "Compete", cantonese: "競爭 (ging3 zang1)", level: 70 },
{ eng: "Skill", cantonese: "技能 (gei6 nang4)", level: 70 },
{ eng: "Concentrate", cantonese: "專心 (zyun1 sam1)", level: 70 },
{ eng: "Quiz / Test", cantonese: "測驗 (cak1 jim6)", level: 70 },
{ eng: "Review", cantonese: "溫習 (wan1 zaap6)", level: 70 },

// L71: Advanced Academics (High School Tier Starts)
{ eng: "Algebra", cantonese: "代數 (doi6 sou3)", level: 71 },
{ eng: "Geometry", cantonese: "幾何 (gei2 ho4)", level: 71 },
{ eng: "Economics", cantonese: "經濟學 (ging1 zai3 hok6)", level: 71 },
{ eng: "Politics", cantonese: "政治 (zing3 zi6)", level: 71 },
{ eng: "Philosophy", cantonese: "哲學 (zit3 hok6)", level: 71 },
{ eng: "Psychology", cantonese: "心理學 (sam1 lei5 hok6)", level: 71 },
{ eng: "Sociology", cantonese: "社會學 (se5 wui2 hok6)", level: 71 },
{ eng: "Notes", cantonese: "筆記 (bat1 gei3)", level: 71 },
{ eng: "Summary", cantonese: "總結 (zung2 git3)", level: 71 },
{ eng: "Deadline", cantonese: "期限 (kei4 haan6)", level: 71 },
{ eng: "Extracurricular", cantonese: "課外活動 (fo3 ngoi6 wut6 dung6)", level: 71 },
{ eng: "Timetable", cantonese: "時間表 (si4 gaan3 biu2)", level: 71 },
{ eng: "Diploma", cantonese: "文憑 (man4 pang4)", level: 71 },
{ eng: "Application", cantonese: "申請 (san1 cing2)", level: 71 },
{ eng: "Exam Prep", cantonese: "備考 (bei6 haau2)", level: 71 },

// L72: Youth & Relationships
{ eng: "Crush", cantonese: "暗戀 (am3 lyun2)", level: 72 },
{ eng: "Date", cantonese: "約會 (joek3 wui6)", level: 72 },
{ eng: "Boyfriend", cantonese: "男朋友 (naam4 pang4 jau5)", level: 72 },
{ eng: "Girlfriend", cantonese: "女朋友 (neoi5 pang4 jau5)", level: 72 },
{ eng: "Break up", cantonese: "分手 (fan1 sau2)", level: 72 },
{ eng: "Heartbreak", cantonese: "失戀 (sat1 lyun2)", level: 72 },
{ eng: "Confess", cantonese: "表白 (biu2 baak6)", level: 72 },
{ eng: "Attractive", cantonese: "吸引 (kap1 jan5)", level: 72 },
{ eng: "Handsome", cantonese: "靚仔 (leng3 zai2)", level: 72 },
{ eng: "Pretty Girl", cantonese: "靚女 (leng3 neoi5)", level: 72 },
{ eng: "Personality", cantonese: "性格 (sing3 gaak3)", level: 72 },
{ eng: "Honest", cantonese: "誠實 (sing4 sat6)", level: 72 },
{ eng: "Hypocrite", cantonese: "虛偽 (heoi1 ngai6)", level: 72 },
{ eng: "Mood", cantonese: "心情 (sam1 cing4)", level: 72 },
{ eng: "Privacy", cantonese: "私隱 (si1 jan2)", level: 72 },

// L73: Modern Digital Life
{ eng: "Post", cantonese: "帖文 (tip3 man4)", level: 73 },
{ eng: "Like", cantonese: "讚好 (zaan3 hou2)", level: 73 },
{ eng: "Comment", cantonese: "留言 (lau4 jin4)", level: 73 },
{ eng: "Forward / Share", cantonese: "轉發 (zyun2 faat3)", level: 73 },
{ eng: "Follow", cantonese: "追蹤 (zeoi1 zung1)", level: 73 },
{ eng: "Block", cantonese: "封鎖 (fung1 so2)", level: 73 },
{ eng: "Profile", cantonese: "個人資料 (go3 jan4 zi1 liu2)", level: 73 },
{ eng: "Notification", cantonese: "通知 (tung1 zi1)", level: 73 },
{ eng: "Influencer", cantonese: "網紅 (mong5 hung4)", level: 73 },
{ eng: "Viral", cantonese: "爆紅 (baau3 hung4)", level: 73 },
{ eng: "Cyberbullying", cantonese: "網絡欺凌 (mong5 lok3 hei1 ling4)", level: 73 },
{ eng: "Account", cantonese: "帳號 (zoeng3 hou6)", level: 73 },
{ eng: "Filter", cantonese: "濾鏡 (leoi6 geng3)", level: 73 },
{ eng: "Meme", cantonese: "迷因 (mai4 jan1)", level: 73 },
{ eng: "Livestream", cantonese: "直播 (zik6 bo3)", level: 73 },

// L74: Practical Life & Responsibilities
{ eng: "Resume", cantonese: "履歷表 (lei5 lik6 biu2)", level: 74 },
{ eng: "Job Interview", cantonese: "面試 (min6 si3)", level: 74 },
{ eng: "Full-time", cantonese: "全職 (cyun4 zik1)", level: 74 },
{ eng: "Qualification", cantonese: "資格 (zi1 gaak3)", level: 74 },
{ eng: "Income", cantonese: "收入 (sau1 jap6)", level: 74 },
{ eng: "Budget", cantonese: "預算 (jyu6 syun3)", level: 74 },
{ eng: "Expense", cantonese: "開支 (hoi1 zi1)", level: 74 },
{ eng: "Bank Account", cantonese: "銀行戶口 (ngan4 hong4 wu6 hau2)", level: 74 },
{ eng: "Transfer money", cantonese: "轉帳 (zyun3 zoeng3)", level: 74 },
{ eng: "Insurance", cantonese: "保險 (bou2 him2)", level: 74 },
{ eng: "Rent", cantonese: "租金 (zou1 gam1)", level: 74 },
{ eng: "Sign", cantonese: "簽署 (cim1 cyu5)", level: 74 },
{ eng: "Driver's License", cantonese: "車牌 (ce1 paai4)", level: 74 },
{ eng: "Independence", cantonese: "獨立 (duk6 laap6)", level: 74 },
{ eng: "Responsibility", cantonese: "責任 (zaak3 jam6)", level: 74 },

// L75: Advanced Descriptive Adjectives
{ eng: "Obvious", cantonese: "明顯 (ming4 hin2)", level: 75 },
{ eng: "Vague", cantonese: "模糊 (mou4 wu4)", level: 75 },
{ eng: "Accurate", cantonese: "準確 (zeon2 kok3)", level: 75 },
{ eng: "Flexible", cantonese: "靈活 (ling4 wut6)", level: 75 },
{ eng: "Stubborn", cantonese: "固執 (gu3 zap1)", level: 75 },
{ eng: "Unique", cantonese: "獨特 (duk6 dak6)", level: 75 },
{ eng: "Normal", cantonese: "正常 (zing3 soeng4)", level: 75 },
{ eng: "Abnormal", cantonese: "唔正常 (m4 zing3 soeng4)", level: 75 },
{ eng: "Strict", cantonese: "嚴格 (jim4 gaak3)", level: 75 },
{ eng: "Casual", cantonese: "隨便 (ceoi4 bin2)", level: 75 },
{ eng: "Optimistic", cantonese: "樂觀 (lok6 gun1)", level: 75 },
{ eng: "Pessimistic", cantonese: "悲觀 (bei1 gun1)", level: 75 },
{ eng: "Traditional", cantonese: "傳統 (cyun4 tung2)", level: 75 },
{ eng: "Modern", cantonese: "現代 (jin6 doi6)", level: 75 },
{ eng: "Rare", cantonese: "罕有 (hon2 jau5)", level: 75 },

// L76: Global Issues & News
{ eng: "World", cantonese: "世界 (sai3 gaai3)", level: 76 },
{ eng: "International", cantonese: "國際 (gwok3 zai3)", level: 76 },
{ eng: "Climate Change", cantonese: "氣候變化 (hei3 hau6 bin3 faa3)", level: 76 },
{ eng: "Disaster", cantonese: "災難 (zoi1 naan6)", level: 76 },
{ eng: "Earthquake", cantonese: "地震 (dei6 zan3)", level: 76 },
{ eng: "Protest", cantonese: "抗議 (kong3 ji5)", level: 76 },
{ eng: "Economy", cantonese: "經濟 (ging1 zai3)", level: 76 },
{ eng: "Policy", cantonese: "政策 (zing3 caak3)", level: 76 },
{ eng: "Development", cantonese: "發展 (faat3 zin2)", level: 76 },
{ eng: "Technology", cantonese: "科技 (fo1 gei6)", level: 76 },
{ eng: "Healthcare", cantonese: "醫療 (ji1 liu4)", level: 76 },
{ eng: "Crisis", cantonese: "危機 (ngai4 gei1)", level: 76 },
{ eng: "Solution", cantonese: "方案 (fong1 on3)", level: 76 },
{ eng: "Agreement", cantonese: "協議 (hip3 ji5)", level: 76 },
{ eng: "Human Rights", cantonese: "人權 (jan4 kyun4)", level: 76 },

// L77: Abstract Thoughts & Communication
{ eng: "Analyze", cantonese: "分析 (fan1 sik1)", level: 77 },
{ eng: "Compare", cantonese: "比較 (bei2 gaau3)", level: 77 },
{ eng: "Criticize", cantonese: "批評 (pai1 ping4)", level: 77 },
{ eng: "Praise", cantonese: "讚美 (zaan3 mei5)", level: 77 },
{ eng: "Explain", cantonese: "解釋 (gaai2 sik1)", level: 77 },
{ eng: "Convince", cantonese: "說服 (seoi3 fuk6)", level: 77 },
{ eng: "Complain", cantonese: "投訴 (tau4 sou3)", level: 77 },
{ eng: "Opinion", cantonese: "意見 (ji3 gin3)", level: 77 },
{ eng: "Fact", cantonese: "事實 (si6 sat6)", level: 77 },
{ eng: "Theory", cantonese: "理論 (lei5 leon6)", level: 77 },
{ eng: "Evidence", cantonese: "證據 (zing3 geoi3)", level: 77 },
{ eng: "Conclusion", cantonese: "結論 (git3 leon6)", level: 77 },
{ eng: "Meaning", cantonese: "意義 (ji3 ji6)", level: 77 },
{ eng: "Attitude", cantonese: "態度 (taai3 dou6)", level: 77 },
{ eng: "Influence", cantonese: "影響 (jing2 hoeng2)", level: 77 },

// L78: Arts, Media, & Culture II
{ eng: "Classic", cantonese: "經典 (ging1 din2)", level: 78 },
{ eng: "Popular", cantonese: "受歡迎 (sau6 fun1 jing4)", level: 78 },
{ eng: "Entertainment", cantonese: "娛樂 (jyu4 lok6)", level: 78 },
{ eng: "Creativity", cantonese: "創意 (cong3 ji3)", level: 78 },
{ eng: "Design", cantonese: "設計 (cit3 gai3)", level: 78 },
{ eng: "Talent", cantonese: "才華 (coi4 waa4)", level: 78 },
{ eng: "Review", cantonese: "評論 (ping4 leon6)", level: 78 },
{ eng: "Award", cantonese: "獎項 (zoeng2 hong6)", level: 78 },
{ eng: "Audience (listening)", cantonese: "聽眾 (ting3 zung3)", level: 78 },
{ eng: "Gallery", cantonese: "畫廊 (waa2 long4)", level: 78 },
{ eng: "Performance", cantonese: "表演 (biu2 jin2)", level: 78 },
{ eng: "Atmosphere", cantonese: "氣氛 (hei3 fan1)", level: 78 },
{ eng: "Style", cantonese: "風格 (fung1 gaak3)", level: 78 },
{ eng: "Inspire", cantonese: "啟發 (kai2 faat3)", level: 78 },
{ eng: "Detail", cantonese: "細節 (sai3 zit3)", level: 78 },

// L79: Career & Workplace
{ eng: "Industry", cantonese: "行業 (hong4 jip6)", level: 79 },
{ eng: "Qualification", cantonese: "資歷 (zi1 lik6)", level: 79 },
{ eng: "Salary / Pay", cantonese: "薪金 (san1 gam1)", level: 79 },
{ eng: "Supervisor", cantonese: "上司 (soeng6 si1)", level: 79 },
{ eng: "Team", cantonese: "團隊 (tyun4 deoi2)", level: 79 },
{ eng: "Client", cantonese: "客戶 (haak3 wu6)", level: 79 },
{ eng: "Project", cantonese: "項目 (hong6 muk6)", level: 79 },
{ eng: "Presentation / Slides", cantonese: "簡報 (gaan2 bou3)", level: 79 },
{ eng: "Promotion", cantonese: "升職 (sing1 zik1)", level: 79 },
{ eng: "Resign", cantonese: "辭職 (ci4 zik1)", level: 79 },
{ eng: "Retire", cantonese: "退休 (teoi3 jau1)", level: 79 },
{ eng: "Overtime", cantonese: "加班 (gaa1 baan1)", level: 79 },
{ eng: "Conference", cantonese: "會議 (wui6 ji5)", level: 79 },
{ eng: "Business Trip", cantonese: "出差 (ceot1 caai1)", level: 79 },
{ eng: "Career", cantonese: "職業 (zik1 jip6)", level: 79 },

// L80: Coming of Age (High School Tier Ends)
{ eng: "Graduation Ceremony", cantonese: "畢業典禮 (bat1 jip6 din2 lai5)", level: 80 },
{ eng: "Prom / Ball", cantonese: "舞會 (mou5 wui2)", level: 80 },
{ eng: "Adult", cantonese: "成人 (sing4 jan4)", level: 80 },
{ eng: "Sense of Responsibility", cantonese: "責任感 (zaak3 jam6 gam2)", level: 80 },
{ eng: "Lease / Tenancy", cantonese: "租約 (zou1 joek3)", level: 80 },
{ eng: "Bills", cantonese: "帳單 (zoeng3 daan1)", level: 80 },
{ eng: "ID Card", cantonese: "身份證 (san1 fan2 zing3)", level: 80 },
{ eng: "Voter", cantonese: "選民 (syun2 man4)", level: 80 },
{ eng: "The Public", cantonese: "大眾 (daai6 zung3)", level: 80 },
{ eng: "Generation", cantonese: "世代 (sai3 doi6)", level: 80 },
{ eng: "Prospects / Future", cantonese: "前途 (cin4 tou4)", level: 80 },
{ eng: "Youth", cantonese: "青春 (cing1 ceon1)", level: 80 },
{ eng: "Mature", cantonese: "成熟 (sing4 suk6)", level: 80 },
{ eng: "Life Experience", cantonese: "歷練 (lik6 lin6)", level: 80 },
{ eng: "Transition", cantonese: "過渡 (gwo3 dou6)", level: 80 },

// L81: Campus Life (University Tier Starts)
{ eng: "University", cantonese: "大學 (daai6 hok6)", level: 81 },
{ eng: "Major (subject)", cantonese: "主修 (zyu2 sau1)", level: 81 },
{ eng: "Degree", cantonese: "學位 (學位 (hok6 wai2)", level: 81 },
{ eng: "Bachelor's", cantonese: "學士 (hok6 si6)", level: 81 },
{ eng: "Master's", cantonese: "碩士 (sek6 si6)", level: 81 },
{ eng: "Dormitory", cantonese: "宿舍 (suk1 se3)", level: 81 },
{ eng: "Roommate", cantonese: "同房 (tung4 fong2)", level: 81 },
{ eng: "Lecture", cantonese: "講座 (gong2 zo6)", level: 81 },
{ eng: "Assignment", cantonese: "作業 (zok3 jip6)", level: 81 },
{ eng: "Thesis", cantonese: "論文 (leon6 man4)", level: 81 },
{ eng: "Financial Aid / Grant", cantonese: "助學金 (zo6 hok6 gam1)", level: 81 },
{ eng: "Credits", cantonese: "學分 (hok6 fan1)", level: 81 },
{ eng: "Postgraduate Student", cantonese: "研究生 (jin4 gau3 saang1)", level: 81 },
{ eng: "Faculty / College", cantonese: "學院 (hok6 jyun2)", level: 81 },
{ eng: "Orientation", cantonese: "迎新 (jing4 san1)", level: 81 },

// L82: Academic Disciplines & Research
{ eng: "Survey / Investigation", cantonese: "調查 (diu6 caa4)", level: 82 },
{ eng: "Laboratory", cantonese: "實驗室 (sat6 jim6 sat1)", level: 82 },
{ eng: "Data", cantonese: "數據 (sou3 geoi3)", level: 82 },
{ eng: "Statistics", cantonese: "統計 (tung2 gai3)", level: 82 },
{ eng: "Hypothesis", cantonese: "假設 (gaa2 cit3)", level: 82 },
{ eng: "Methodology", cantonese: "研究方法 (jin4 gau3 fong1 faat3)", level: 82 },
{ eng: "Reference", cantonese: "參考 (caam1 haau2)", level: 82 },
{ eng: "Source", cantonese: "來源 (loi4 jyun4)", level: 82 },
{ eng: "Publish", cantonese: "出版 (ceot1 baan2)", level: 82 },
{ eng: "Academic Journal", cantonese: "期刊 (kei4 hon2)", level: 82 },
{ eng: "Debate", cantonese: "辯論 (bin6 leon6)", level: 82 },
{ eng: "Seminar", cantonese: "研討會 (jin4 tou2 wui2)", level: 82 },
{ eng: "Present / Announce", cantonese: "發表 (faat3 biu2)", level: 82 },
{ eng: "Expert", cantonese: "專家 (zyun1 gaa1)", level: 82 },
{ eng: "Academic", cantonese: "學術 (hok6 seot6)", level: 82 },

// L83: University Social Life & Networking
{ eng: "Internship", cantonese: "實習 (sat6 zaap6)", level: 83 },
{ eng: "Exchange Student", cantonese: "交換生 (gaau1 wun6 saang1)", level: 83 },
{ eng: "Mentor", cantonese: "導師 (dou6 si1)", level: 83 },
{ eng: "Tutor", cantonese: "補習老師 (bou2 zaap6 lou5 si1)", level: 83 },
{ eng: "Connections / Network", cantonese: "人脈 (jan4 mak6)", level: 83 },
{ eng: "Gathering", cantonese: "聚會 (zeoi6 wui6)", level: 83 },
{ eng: "Orientation Camp", cantonese: "迎新營 (jing4 san1 jing4)", level: 83 },
{ eng: "Culture Shock", cantonese: "文化衝擊 (man4 faa3 cung1 gik1)", level: 83 },
{ eng: "Homesick", cantonese: "掛住屋企 (gwaa3 zyu6 uk1 kei2)", level: 83 },
{ eng: "Stay up late", cantonese: "熬夜 (ngou4 je6)", level: 83 },
{ eng: "Hangover", cantonese: "宿醉 (suk1 zeoi3)", level: 83 },
{ eng: "Canteen / Cafeteria", cantonese: "飯堂 (faan6 tong4)", level: 83 },
{ eng: "Study / Revise", cantonese: "溫書 (wan1 syu1)", level: 83 },
{ eng: "Partying", cantonese: "狂歡 (kwong4 fun1)", level: 83 },
{ eng: "Club / Society (Uni)", cantonese: "學會 (hok6 wui2)", level: 83 },

// L84: Advanced Ideas & Philosophy
{ eng: "Objective", cantonese: "客觀 (haak3 gun1)", level: 84 },
{ eng: "Subjective", cantonese: "主觀 (zyu2 gun1)", level: 84 },
{ eng: "Bias", cantonese: "偏見 (pin1 gin3)", level: 84 },
{ eng: "Diversity", cantonese: "多元化 (do1 jyun4 faa3)", level: 84 },
{ eng: "Balance", cantonese: "平衡 (ping4 hang4)", level: 84 },
{ eng: "Phenomenon", cantonese: "現象 (jin6 zoeng6)", level: 84 },
{ eng: "Concept", cantonese: "概念 (koi3 nim6)", level: 84 },
{ eng: "Principle", cantonese: "原則 (jyun4 zak1)", level: 84 },
{ eng: "Reality", cantonese: "現實 (jin6 sat6)", level: 84 },
{ eng: "Illusion", cantonese: "幻覺 (waan6 gok3)", level: 84 },
{ eng: "Rationality", cantonese: "理性 (lei5 sing3)", level: 84 },
{ eng: "Emotion / Feeling", cantonese: "情感 (cing4 gam2)", level: 84 },
{ eng: "Morality / Ethics", cantonese: "道德 (dou6 dak1)", level: 84 },
{ eng: "Trend", cantonese: "趨勢 (ceoi1 sai3)", level: 84 },
{ eng: "Value (concept)", cantonese: "價值 (gaa3 zik6)", level: 84 },

// L85: Global Topics & Systems
{ eng: "Globalization", cantonese: "全球化 (cyun4 kau4 faa3)", level: 85 },
{ eng: "Sustainability", cantonese: "可持續性 (ho2 ci4 zuk6 sing3)", level: 85 },
{ eng: "Ecosystem", cantonese: "生態系統 (sang1 taai3 hai6 tung2)", level: 85 },
{ eng: "Conservation", cantonese: "保育 (bou2 juk6)", level: 85 },
{ eng: "Energy", cantonese: "能源 (nang4 jyun4)", level: 85 },
{ eng: "Resource", cantonese: "資源 (zi1 jyun4)", level: 85 },
{ eng: "Activist", cantonese: "社運人士 (se5 wan6 jan4 si6)", level: 85 },
{ eng: "System", cantonese: "制度 (zai3 dou6)", level: 85 },
{ eng: "Organization", cantonese: "組織 (zou2 zik1)", level: 85 },
{ eng: "Contribution", cantonese: "貢獻 (gung3 hin3)", level: 85 },
{ eng: "Refugee", cantonese: "難民 (naan6 man4)", level: 85 },
{ eng: "Humanitarian", cantonese: "人道 (jan4 dou6)", level: 85 },
{ eng: "Famine", cantonese: "飢荒 (gei1 fong1)", level: 85 },
{ eng: "Democracy", cantonese: "民主 (man4 zyu2)", level: 85 },
{ eng: "Freedom of Speech", cantonese: "言論自由 (jin4 leon6 zi6 jau4)", level: 85 },

// L86: Independent Living & Chores
{ eng: "Landlord", cantonese: "業主 (jip6 zyu2)", level: 86 },
{ eng: "Tenant", cantonese: "租客 (zou1 haak3)", level: 86 },
{ eng: "Utilities (Water/Elec)", cantonese: "水電費 (seoi2 din6 fai3)", level: 86 },
{ eng: "Grocery Shopping", cantonese: "買餸 (maai5 sung3)", level: 86 },
{ eng: "Recipe", cantonese: "食譜 (sik6 pou2)", level: 86 },
{ eng: "Home Appliance", cantonese: "電器 (din6 hei3)", level: 86 },
{ eng: "Plumber", cantonese: "水喉佬 (seoi2 hau4 lou2)", level: 86 },
{ eng: "Electrician", cantonese: "電工 (din6 gung1)", level: 86 },
{ eng: "Financial Management", cantonese: "理財 (lei5 coi4)", level: 86 },
{ eng: "Frugal / Save money", cantonese: "慳錢 (haan1 cin4)", level: 86 },
{ eng: "Washing Machine", cantonese: "洗衣機 (sai2 ji1 gei1)", level: 86 },
{ eng: "Ironing clothes", cantonese: "燙衫 (tong3 saam1)", level: 86 },
{ eng: "Housework", cantonese: "家務 (gaa1 mou6)", level: 86 },
{ eng: "Vacuum Cleaner", cantonese: "吸塵機 (kap1 can4 gei1)", level: 86 },
{ eng: "Refrigerator", cantonese: "雪櫃 (syut3 gwai3)", level: 86 },

// L87: Advanced Communication & Socializing
{ eng: "Express (feelings)", cantonese: "表達 (biu2 daat6)", level: 87 },
{ eng: "Communicate", cantonese: "溝通 (kau1 tung1)", level: 87 },
{ eng: "Misunderstanding", cantonese: "誤會 (ng6 wui6)", level: 87 },
{ eng: "Compromise", cantonese: "讓步 (joeng6 bou6)", level: 87 },
{ eng: "Empathy", cantonese: "同理心 (tung4 lei5 sam1)", level: 87 },
{ eng: "Sarcasm", cantonese: "諷刺 (fung3 ci3)", level: 87 },
{ eng: "Humor", cantonese: "幽默 (jau1 mak6)", level: 87 },
{ eng: "Awkward", cantonese: "尷尬 (gaam1 gaai3)", level: 87 },
{ eng: "Vibe / Atmosphere", cantonese: "氣氛 (hei3 fan1)", level: 87 },
{ eng: "Intimate", cantonese: "親密 (can1 mat6)", level: 87 },
{ eng: "Alienate", cantonese: "疏遠 (so1 jyun5)", level: 87 },
{ eng: "Gossiping", cantonese: "講是非 (gong2 si6 fei1)", level: 87 },
{ eng: "Hypocritical", cantonese: "虛偽 (heoi1 ngai6)", level: 87 },
{ eng: "Genuine / Sincere", cantonese: "真誠 (zan1 sing4)", level: 87 },
{ eng: "Boundaries", cantonese: "界線 (gaai3 sin3)", level: 87 },

// L88: Health, Wellness & Psychology
{ eng: "Mental health", cantonese: "精神健康 (zing1 san4 gin6 hong1)", level: 88 },
{ eng: "Depression", cantonese: "抑鬱症 (jik1 wat1 zing3)", level: 88 },
{ eng: "Anxiety", cantonese: "焦慮症 (ziu1 leoi6 zing3)", level: 88 },
{ eng: "Therapy", cantonese: "心理治療 (sam1 lei5 zi6 liu4)", level: 88 },
{ eng: "Meditation", cantonese: "冥想 (ming5 soeng2)", level: 88 },
{ eng: "Mindfulness", cantonese: "正念 (zing3 nim6)", level: 88 },
{ eng: "Nutrition", cantonese: "營養 (jing4 joeng5)", level: 88 },
{ eng: "Immune system", cantonese: "免疫系統 (min5 jik6 hai6 tung2)", level: 88 },
{ eng: "Vaccine", cantonese: "疫苗 (jik6 miu4)", level: 88 },
{ eng: "Side effect", cantonese: "副作用 (fu3 zok3 jung6)", level: 88 },
{ eng: "Metabolism", cantonese: "新陳代謝 (san1 can4 doi6 ze6)", level: 88 },
{ eng: "Addiction", cantonese: "上癮 (soeng5 jan5)", level: 88 },
{ eng: "Recovery", cantonese: "康復 (hong1 fuk6)", level: 88 },
{ eng: "Well-being", cantonese: "福祉 (fuk1 zi2)", level: 88 },
{ eng: "Insomnia", cantonese: "失眠 (sat1 min4)", level: 88 },

// L89: Arts, Literature & Criticism
{ eng: "Masterpiece", cantonese: "傑作 (git6 zok3)", level: 89 },
{ eng: "Abstract", cantonese: "抽象 (cau1 zoeng6)", level: 89 },
{ eng: "Aesthetic", cantonese: "美感 (mei5 gam2)", level: 89 },
{ eng: "Metaphor", cantonese: "暗喻 (am3 jyu6)", level: 89 },
{ eng: "Symbol", cantonese: "象徵 (zoeng6 zing1)", level: 89 },
{ eng: "Context", cantonese: "語境 (jyu5 ging2)", level: 89 },
{ eng: "Narrative", cantonese: "敘事 (zeoi6 si6)", level: 89 },
{ eng: "Perspective", cantonese: "視角 (si6 gok3)", level: 89 },
{ eng: "Protagonist", cantonese: "主角 (zyu2 gok3)", level: 89 },
{ eng: "Antagonist", cantonese: "反派 (faan2 paai3)", level: 89 },
{ eng: "Climax (story)", cantonese: "高潮 (gou1 ciu4)", level: 89 },
{ eng: "Tragedy", cantonese: "悲劇 (bei1 kek6)", level: 89 },
{ eng: "Comedy", cantonese: "喜劇 (hei2 kek6)", level: 89 },
{ eng: "Genre", cantonese: "類型 (leoi6 jing4)", level: 89 },
{ eng: "Critique / Review", cantonese: "評論 (ping4 leon6)", level: 89 },

// L90: End of University / Transition
{ eng: "Graduation", cantonese: "畢業 (bat1 jip6)", level: 90 },
{ eng: "Alumni", cantonese: "校友 (haau3 jau5)", level: 90 },
{ eng: "Job market", cantonese: "就業市場 (zau6 jip6 si5 coeng4)", level: 90 },
{ eng: "Recruitment", cantonese: "招聘 (ziu1 ping3)", level: 90 },
{ eng: "Networking", cantonese: "建立人脈 (gin3 laap6 jan4 mak6)", level: 90 },
{ eng: "Startup", cantonese: "初創企業 (co1 cong3 kei5 jip6)", level: 90 },
{ eng: "Entrepreneur", cantonese: "企業家 (kei5 jip6 gaa1)", level: 90 },
{ eng: "Innovation", cantonese: "創新 (cong3 san1)", level: 90 },
{ eng: "Strategy", cantonese: "策略 (caak3 loek6)", level: 90 },
{ eng: "Efficiency", cantonese: "效率 (haau6 leot6)", level: 90 },
{ eng: "Productivity", cantonese: "生產力 (saang1 caan2 lik6)", level: 90 },
{ eng: "Deadline", cantonese: "死線 (sei2 sin3)", level: 90 },
{ eng: "Colleague", cantonese: "同事 (tung4 si6)", level: 90 },
{ eng: "Business trip", cantonese: "出差 (ceot1 caai1)", level: 90 },
{ eng: "Corporate culture", cantonese: "企業文化 (kei5 jip6 man4 faa3)", level: 90 },

// L91: Office & Corporate Environment (Business Tier Starts)
{ eng: "Headquarters", cantonese: "總部 (zung2 bou6)", level: 91 },
{ eng: "Branch Office", cantonese: "分公司 (fan1 gung1 si1)", level: 91 },
{ eng: "Department", cantonese: "部門 (bou6 mun4)", level: 91 },
{ eng: "Human Resources (HR)", cantonese: "人事部 (jan4 si6 bou6)", level: 91 },
{ eng: "Board of Directors", cantonese: "董事會 (dung2 si6 wui2)", level: 91 },
{ eng: "CEO", cantonese: "行政總裁 (hang4 zing3 zung2 coi4)", level: 91 },
{ eng: "Management", cantonese: "管理層 (gun2 lei5 cang4)", level: 91 },
{ eng: "Employee / Staff", cantonese: "職員 (zik1 jyun4)", level: 91 },
{ eng: "Cubicle / Desk", cantonese: "辦公桌 (baan6 gung1 coek3)", level: 91 },
{ eng: "Meeting Room", cantonese: "會議室 (wui6 ji5 sat1)", level: 91 },
{ eng: "Photocopier", cantonese: "影印機 (jing2 jan3 gei1)", level: 91 },
{ eng: "Document", cantonese: "文件 (man4 gin2)", level: 91 },
{ eng: "Report", cantonese: "報告 (bou3 gou3)", level: 91 },
{ eng: "Memo / Notice", cantonese: "通告 (tung1 gou3)", level: 91 },
{ eng: "Workplace", cantonese: "工作場所 (gung1 zok3 coeng4 so2)", level: 91 },

// L92: Meetings & Negotiations
{ eng: "Agenda", cantonese: "議程 (ji5 cing4)", level: 92 },
{ eng: "Minutes (of meeting)", cantonese: "會議紀錄 (wui6 ji5 gei3 luk6)", level: 92 },
{ eng: "Proposal", cantonese: "計劃書 (gai3 waak6 syu1)", level: 92 },
{ eng: "Negotiate", cantonese: "談判 (taam4 pun3)", level: 92 },
{ eng: "Compromise", cantonese: "妥協 (to5 hip3)", level: 92 },
{ eng: "Terms and Conditions", cantonese: "條款 (tiu4 fun2)", level: 92 },
{ eng: "Contract", cantonese: "合約 (hap6 joek3)", level: 92 },
{ eng: "Sign", cantonese: "簽名 (cim1 ming2)", level: 92 },
{ eng: "Deadline", cantonese: "最後限期 (zeoi3 hau6 haan6 kei4)", level: 92 },
{ eng: "Approve", cantonese: "批准 (pai1 zeon2)", level: 92 },
{ eng: "Reject", cantonese: "拒絕 (keoi5 zyut6)", level: 92 },
{ eng: "Feedback", cantonese: "意見回饋 (ji3 gin3 wui4 gwai3)", level: 92 },
{ eng: "Consensus", cantonese: "共識 (gung6 sik1)", level: 92 },
{ eng: "Postpone", cantonese: "延期 (jin4 kei4)", level: 92 },
{ eng: "Cancel", cantonese: "取消 (ceoi2 siu1)", level: 92 },

// L93: Finance & Accounting
{ eng: "Revenue", cantonese: "收入 (sau1 jap6)", level: 93 },
{ eng: "Profit", cantonese: "利潤 (lei6 jeon6)", level: 93 },
{ eng: "Loss", cantonese: "虧損 (kwai1 syun2)", level: 93 },
{ eng: "Budget", cantonese: "預算 (jyu6 syun3)", level: 93 },
{ eng: "Expense", cantonese: "開支 (hoi1 zi1)", level: 93 },
{ eng: "Investment", cantonese: "投資 (tau4 zi1)", level: 93 },
{ eng: "Shareholder", cantonese: "股東 (gu2 dung1)", level: 93 },
{ eng: "Stock Market", cantonese: "股票市場 (gu2 piu3 si5 coeng4)", level: 93 },
{ eng: "Dividend", cantonese: "股息 (gu2 sik1)", level: 93 },
{ eng: "Tax", cantonese: "稅 (seoi3)", level: 93 },
{ eng: "Audit", cantonese: "審計 (sam2 gai3)", level: 93 },
{ eng: "Invoice", cantonese: "發票 (faat3 piu3)", level: 93 },
{ eng: "Receipt", cantonese: "收據 (sau1 geoi3)", level: 93 },
{ eng: "Bank Account", cantonese: "銀行戶口 (ngan4 hong4 wu6 hau2)", level: 93 },
{ eng: "Interest Rate", cantonese: "利率 (lei6 leot6)", level: 93 },

// L94: Marketing & Sales
{ eng: "Marketing", cantonese: "市場營銷 (si5 coeng4 jing4 siu1)", level: 94 },
{ eng: "Campaign", cantonese: "宣傳活動 (syun1 cyun4 wut6 dung6)", level: 94 },
{ eng: "Target Audience", cantonese: "目標受眾 (muk6 biu1 sau6 zung3)", level: 94 },
{ eng: "Brand", cantonese: "品牌 (pan2 paai4)", level: 94 },
{ eng: "Product", cantonese: "產品 (caan2 ban2)", level: 94 },
{ eng: "Service", cantonese: "服務 (fuk6 mou6)", level: 94 },
{ eng: "Customer", cantonese: "顧客 (gu3 haak3)", level: 94 },
{ eng: "Competitor", cantonese: "競爭對手 (ging3 zang1 deoi3 sau2)", level: 94 },
{ eng: "Market Share", cantonese: "市場佔有率 (si5 coeng4 zim3 jau5 leot6)", level: 94 },
{ eng: "Trend", cantonese: "趨勢 (ceoi1 sai3)", level: 94 },
{ eng: "Discount", cantonese: "折扣 (zik3 kau3)", level: 94 },
{ eng: "Wholesale", cantonese: "批發 (pai1 faat3)", level: 94 },
{ eng: "Retail", cantonese: "零售 (ling4 sau6)", level: 94 },
{ eng: "Launch (product)", cantonese: "推出 (teoi1 ceot1)", level: 94 },
{ eng: "Review / Rating", cantonese: "評價 (ping4 gaa3)", level: 94 },

// L95: Business Operations & Logistics
{ eng: "Supply Chain", cantonese: "供應鏈 (gung1 jing3 lin2)", level: 95 },
{ eng: "Logistics", cantonese: "物流 (mat6 lau4)", level: 95 },
{ eng: "Inventory", cantonese: "存貨 (cyun4 fo3)", level: 95 },
{ eng: "Warehouse", cantonese: "貨倉 (fo3 cong1)", level: 95 },
{ eng: "Supplier", cantonese: "供應商 (gung1 jing3 soeng1)", level: 95 },
{ eng: "Distributor", cantonese: "分銷商 (fan1 siu1 soeng1)", level: 95 },
{ eng: "Import", cantonese: "進口 (zeon3 hau2)", level: 95 },
{ eng: "Export", cantonese: "出口 (ceot1 hau2)", level: 95 },
{ eng: "Shipping", cantonese: "運輸 (wan6 syu1)", level: 95 },
{ eng: "Delivery", cantonese: "送貨 (sung3 fo3)", level: 95 },
{ eng: "Freight", cantonese: "貨運 (fo3 wan6)", level: 95 },
{ eng: "Customs", cantonese: "海關 (hoi2 gwaan1)", level: 95 },
{ eng: "Quality Control", cantonese: "品質控制 (ban2 zat1 hung3 zai3)", level: 95 },
{ eng: "Efficiency", cantonese: "效率 (haau6 leot6)", level: 95 },
{ eng: "Maintenance", cantonese: "維修保養 (wai4 sau1 bou2 joeng2)", level: 95 },

// L96: Human Resources & Employment
{ eng: "Job Application", cantonese: "求職申請 (kau4 zik1 san1 cing2)", level: 96 },
{ eng: "Hire", cantonese: "聘請 (ping3 cing2)", level: 96 },
{ eng: "Fire / Dismiss", cantonese: "解僱 (gaai2 gu3)", level: 96 },
{ eng: "Day Off / Leave", cantonese: "請假 (cing2 gaa3)", level: 96 },
{ eng: "Annual Leave", cantonese: "年假 (nin4 gaa3)", level: 96 },
{ eng: "Sick Leave", cantonese: "病假 (beng6 gaa3)", level: 96 },
{ eng: "Maternity Leave", cantonese: "產假 (caan2 gaa3)", level: 96 },
{ eng: "Benefits", cantonese: "福利 (fuk1 lei6)", level: 96 },
{ eng: "Bonus", cantonese: "花紅 (faa1 hung4)", level: 96 },
{ eng: "Allowance", cantonese: "津貼 (zeon1 tip3)", level: 96 },
{ eng: "Payroll", cantonese: "薪酬 (san1 cau4)", level: 96 },
{ eng: "Training", cantonese: "培訓 (pui4 fan3)", level: 96 },
{ eng: "Appraisal", cantonese: "評估 (ping4 gu2)", level: 96 },
{ eng: "Pension", cantonese: "退休金 (teoi3 jau1 gam1)", level: 96 },
{ eng: "Contractor", cantonese: "外判商 (ngoi6 pun3 soeng1)", level: 96 },

// L97: Corporate Strategy & Law
{ eng: "Vision", cantonese: "願景 (jyun6 ging2)", level: 97 },
{ eng: "Mission", cantonese: "使命 (si2 ming6)", level: 97 },
{ eng: "Research and Development", cantonese: "研發 (jin4 faat3)", level: 97 },
{ eng: "Patent", cantonese: "專利 (zyun1 lei6)", level: 97 },
{ eng: "Copyright", cantonese: "版權 (baan2 kyun4)", level: 97 },
{ eng: "Trademark", cantonese: "商標 (soeng1 biu1)", level: 97 },
{ eng: "Merger", cantonese: "合併 (hap6 ping3)", level: 97 },
{ eng: "Acquisition", cantonese: "收購 (sau1 gau3)", level: 97 },
{ eng: "Partnership", cantonese: "合作夥伴 (hap6 zok3 fo2 bun6)", level: 97 },
{ eng: "Outsource", cantonese: "外判 (ngoi6 pun3)", level: 97 },
{ eng: "Consultant", cantonese: "顧問 (gu3 man6)", level: 97 },
{ eng: "Risk Management", cantonese: "風險管理 (fung1 him2 gun2 lei5)", level: 97 },
{ eng: "Bankruptcy", cantonese: "破產 (po3 caan2)", level: 97 },
{ eng: "Lawsuit", cantonese: "官司 (gun1 si1)", level: 97 },
{ eng: "Compliance", cantonese: "合規 (hap6 kwai1)", level: 97 },

// L98: IT & Cybersecurity in Business
{ eng: "Database", cantonese: "資料庫 (zi1 liu2 fu3)", level: 98 },
{ eng: "Server", cantonese: "伺服器 (zi6 fuk6 hei3)", level: 98 },
{ eng: "Cloud Computing", cantonese: "雲端計算 (wan4 dyun1 gai3 syun3)", level: 98 },
{ eng: "Cybersecurity", cantonese: "網絡安全 (mong5 lok3 on1 cyun4)", level: 98 },
{ eng: "Hacker", cantonese: "黑客 (hak1 haak3)", level: 98 },
{ eng: "Virus", cantonese: "病毒 (beng6 duk6)", level: 98 },
{ eng: "Firewall", cantonese: "防火牆 (fong4 fo2 coeng4)", level: 98 },
{ eng: "Software", cantonese: "軟件 (jyun5 gin2)", level: 98 },
{ eng: "Hardware", cantonese: "硬件 (ngang6 gin2)", level: 98 },
{ eng: "Update", cantonese: "更新 (gang1 san1)", level: 98 },
{ eng: "Upgrade", cantonese: "升級 (sing1 gap1)", level: 98 },
{ eng: "Troubleshoot", cantonese: "疑難排解 (ji4 naan4 paai4 gaai2)", level: 98 },
{ eng: "Backup", cantonese: "備份 (bei6 fan6)", level: 98 },
{ eng: "Tech Support", cantonese: "技術支援 (gei6 seot6 zi1 jyun4)", level: 98 },
{ eng: "System Crash", cantonese: "死機 (sei2 gei1)", level: 98 },

// L99: Economics & Global Trade
{ eng: "Macroeconomics", cantonese: "宏觀經濟 (wang4 gun1 ging1 zai3)", level: 99 },
{ eng: "Inflation", cantonese: "通貨膨脹 (tung1 fo3 paang4 zoeng3)", level: 99 },
{ eng: "Deflation", cantonese: "通貨緊縮 (tung1 fo3 gan2 suk1)", level: 99 },
{ eng: "Recession", cantonese: "經濟衰退 (ging1 zai3 seoi1 teoi3)", level: 99 },
{ eng: "Monopoly", cantonese: "壟斷 (lung5 dyun6)", level: 99 },
{ eng: "Tariff", cantonese: "關稅 (gwaan1 seoi3)", level: 99 },
{ eng: "Subsidy", cantonese: "補貼 (bou2 tip3)", level: 99 },
{ eng: "Exchange Rate", cantonese: "匯率 (wui6 leot6)", level: 99 },
{ eng: "Commodity", cantonese: "商品 (soeng1 ban2)", level: 99 },
{ eng: "Sanction", cantonese: "制裁 (zai3 coi4)", level: 99 },
{ eng: "Free Trade", cantonese: "自由貿易 (zi6 jau4 mau6 jik6)", level: 99 },
{ eng: "Supply and Demand", cantonese: "供求 (gung1 kau4)", level: 99 },
{ eng: "Gross Domestic Product (GDP)", cantonese: "本地生產總值 (bun2 dei6 saang1 caan2 zung2 zik6)", level: 99 },
{ eng: "Capital", cantonese: "資金 (zi1 gam1)", level: 99 },
{ eng: "Revenue Stream", cantonese: "收入來源 (sau1 jap6 loi4 jyun4)", level: 99 },

// L100: Executive Leadership & Strategy
{ eng: "Leadership", cantonese: "領導才能 (ling5 dou6 coi4 nang4)", level: 100 },
{ eng: "Stakeholder", cantonese: "持份者 (ci4 fan6 ze2)", level: 100 },
{ eng: "Business Ethics", cantonese: "商業操守 (soeng1 jip6 cou1 sau2)", level: 100 },
{ eng: "Transparency", cantonese: "透明度 (tau3 ming4 dou6)", level: 100 },
{ eng: "Accountability", cantonese: "問責性 (man6 zaak3 sing3)", level: 100 },
{ eng: "Synergy", cantonese: "協同效應 (hip3 tung4 haau6 jing3)", level: 100 },
{ eng: "Leverage", cantonese: "槓桿作用 (gung3 gon1 zok3 jung6)", level: 100 },
{ eng: "Best Practice", cantonese: "最佳實踐 (zeoi3 gaai1 sat6 cin5)", level: 100 },
{ eng: "Benchmark", cantonese: "基準 (gei1 zeon2)", level: 100 },
{ eng: "Milestone", cantonese: "里程碑 (lei5 cing4 bei1)", level: 100 },
{ eng: "Roadmap", cantonese: "路線圖 (lou6 sin3 tou4)", level: 100 },
{ eng: "Scalable", cantonese: "可擴展 (ho2 kwong3 zin2)", level: 100 },
{ eng: "Turnaround (Business)", cantonese: "轉虧為盈 (zyun2 kwai1 wai4 jing4)", level: 100 },
{ eng: "Visionary", cantonese: "有遠見 (jau5 jyun5 gin3)", level: 100 },
{ eng: "Execution", cantonese: "執行 (zak1 hang4)", level: 100 }
];